(() => {
 const S=window.SkiOps,{head,panel,button,link,status,money,date,field,esc}=S;
 const payments=[['R-025','김민수','현금',100000],['R-025','김민수','카드',200000],['R-021','김영희','카드',65000],['R-022','박준호','계좌이체',50000],['R-023','이수진','카드',60000],['R-024','최은정','현금',30000],['R-026','정하늘','카드',180000],['R-027','윤서준','계좌이체',50000]];
 const received=payments.reduce((sum,p)=>sum+p[3],0),partnerReceived=S.data.trades.filter(t=>t.direction==='get').reduce((n,t)=>n+t.paid,0),partnerPaid=S.data.trades.filter(t=>t.direction==='pay').reduce((n,t)=>n+t.paid,0);
 const customerDue=S.data.orders.reduce((n,o)=>n+o.amount-o.paid,0),partnerDue=S.data.partners.reduce((n,p)=>n+p.get,0),payable=S.data.partners.reduce((n,p)=>n+p.pay,0);
 const lines=rows=>rows.map(([l,n,c])=>'<div class="so-summary-line '+(c||'')+'"><span>'+l+'</span><strong class="so-money">'+(typeof n==='number'?money(n):n)+'</strong></div>').join('');
 const metric=(l,n,route,accent='')=>'<button type="button" class="so-metric '+accent+'" data-action="closing-tab" data-id="'+route+'"><span class="so-metric-label">'+l+'</span><strong>'+n.toLocaleString('ko-KR')+'<em>원</em></strong></button>';
 function receipt(){return '<p>우리 스키샵 · '+date(S.data.today)+' 영업 마감 예시</p><div>'+lines([['고객 신규 확정액',S.data.orders.reduce((n,o)=>n+o.amount,0)],['업체 판매·대여 확정액',280000],['고객에게 받은 대금',received],['업체에서 받은 대금',partnerReceived],['업체에 지급한 대금',partnerPaid],['환불',0],['받을 잔액 합계',customerDue+partnerDue],['줄 잔액 합계',payable],['보증금 보관 잔액',30000]])+'</div>';
 }
 function render(){const t=S.state.tabs.closing||'summary',selected=S.state.filters.closingDate||S.data.today;const top=head('하루 마감','거래 금액과 실제 돈의 이동을 구분해서 확인하세요.',field('영업일',selected,'date','data-change="closing-date"')+status('마감 전 · 샘플','orange')+button('마감표 미리보기','closing-report','','primary'));
  if(selected!==S.data.today)return top+'<div class="so-panel"><p class="so-empty">선택한 영업일의 샘플 내역이 없습니다.</p><div class="so-panel-pad">'+button('오늘 보기','closing-today','','soft')+'</div></div>';
  let body='';
  if(t==='summary')body='<div class="so-grid2">'+panel('오늘 거래와 대금','<div class="so-panel-pad">'+lines([['고객 신규 확정액',S.data.orders.reduce((n,o)=>n+o.amount,0)],['업체 판매·대여 확정액',280000],['업체 매입·차입 대여료',680000],['고객에게 받은 대금',received],['업체에서 받은 대금',partnerReceived],['오늘 받은 대금 합계',received+partnerReceived,'total']])+'<p class="so-preview-note">매입 비용을 매출에 더하지 않습니다. 거래를 등록한 금액과 실제 수납을 구분합니다.</p></div>')+panel('마지막 확인','<div class="so-panel-pad so-stack"><div class="so-summary-line"><span>매장 반납 확인 대기</span>'+link('1건 확인','rental','R-024','small soft')+'</div><div class="so-summary-line"><span>미수 고객</span>'+link('3명 확인','rentals','','small')+'</div><div class="so-summary-line"><span>보증금 보관</span><strong>'+money(30000)+'</strong></div>'+button('마감 확인 화면','closing-review','','primary')+'<p class="so-muted">미수·미반납이 있어도 해당 내역을 남기고 마감합니다.</p></div>')+'</div>';
  if(t==='payments')body=panel('받은 대금 내역','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>고객·거래</th><th>수단</th><th>받은 금액</th><th></th></tr></thead><tbody>'+payments.map(([id,name,method,n])=>'<tr><td><strong>'+name+'</strong><small>'+id+'</small></td><td>'+method+'</td><td class="so-money">'+money(n)+'</td><td>'+link('대여 상세','rental',id,'small')+'</td></tr>').join('')+'<tr><td><strong>서린스키</strong><small>T-004 · 업체 정산</small></td><td>계좌이체</td><td>'+money(100000)+'</td><td>'+link('거래처 상세','partner','P-003','small')+'</td></tr></tbody></table></div>');
  if(t==='cash')body='<div class="so-grid2">'+panel('예상 마감 현금','<div class="so-panel-pad">'+lines([['시작 시재',100000],['고객 현금 수납',130000],['현금 보증금 수령',30000],['현금 기타 지출',-20000],['예상 마감 현금',240000,'total']])+'<p class="so-preview-note">카드·계좌이체와 상계는 현금 서랍에 포함하지 않습니다.</p></div>')+panel('실제 현금 대조','<div class="so-panel-pad so-stack">'+field('실제로 센 현금',240000,'number','min="0" data-cash-count')+button('차이 확인','cash-check','','primary')+'<p class="so-muted">보증금과 현금 지출을 포함해 비교하는 예시입니다.</p></div>')+'</div>';
  if(t==='unpaid')body='<div class="so-grid2">'+panel('받을 돈','<div class="so-panel-pad">'+S.data.orders.filter(o=>o.amount>o.paid).map(o=>'<div class="so-summary-line"><span>'+link(o.name,'rental',o.id,'quiet small')+'</span><strong>'+money(o.amount-o.paid)+'</strong></div>').join('')+S.data.partners.filter(p=>p.get).map(p=>'<div class="so-summary-line"><span>'+link(p.name,'partner',p.id,'quiet small')+'</span><strong>'+money(p.get)+'</strong></div>').join('')+lines([['합계',customerDue+partnerDue,'total']])+'</div>')+panel('줄 돈','<div class="so-panel-pad">'+S.data.partners.filter(p=>p.pay).map(p=>'<div class="so-summary-line"><span>'+link(p.name,'partner',p.id,'quiet small')+'</span><strong>'+money(p.pay)+'</strong></div>').join('')+'<p class="so-preview-note">받을 돈과 줄 돈은 자동으로 상계하지 않습니다.</p></div>')+'</div>';
  return top+'<div class="so-metrics">'+metric('오늘 받은 대금',received+partnerReceived,'payments')+metric('오늘 지급한 대금',partnerPaid,'summary')+metric('받을 잔액',customerDue+partnerDue,'unpaid','accent')+metric('줄 잔액',payable,'unpaid')+'</div>'+S.tabs([['summary','마감 요약'],['payments','수납 내역'],['cash','현금 대조'],['unpaid','미수·미지급']],'summary')+body;
 }
 S.action('closing-tab',id=>{S.state.tabs.closing=id;S.render();});S.change('closing-date',v=>{S.state.filters.closingDate=v;S.render();});S.action('closing-today',()=>{S.state.filters.closingDate=S.data.today;S.render();});
 S.action('closing-report',()=>S.preview('하루 마감표',receipt()));
 S.action('closing-review',()=>S.preview('마감 전 확인','<div class="so-stack">'+['수납·지급 내역을 확인했어요','현금 서랍 금액을 확인했어요','미수·반납 대기 내역을 확인했어요'].map(label=>'<label class="so-check"><input type="checkbox">'+label+'</label>').join('')+'</div><p class="so-note">마감 확인 화면의 예시입니다. 실제 마감을 확정하거나 잠그지 않습니다.</p>'));
 S.action('cash-check',()=>{const input=S.$('[data-cash-count]'),n=Number(input.value);if(!input.value.trim()||!Number.isFinite(n)||n<0){S.toast('현금 금액을 입력해 주세요.');return;}S.preview('현금 대조 결과','<div>'+lines([['예상 마감 현금',240000],['직접 입력한 현금',n],['차이',n-240000,'total']])+'</div><p>'+(n===240000?'예상 금액과 일치합니다.':'시재·수납·지출 내역을 다시 확인하는 화면입니다.')+'</p>');});
 S.register('closing',{title:'하루 마감',render});
})();
