(() => {
 const S=window.SkiOps,{head,panel,button,link,status,field,select,icon,esc}=S;
 const qr='__GUIDE_QR_DATA_URI__',url='https://rosookwan.github.io/ski-rent-ops/?view=guest-guide';
 const faq=[['장비를 매장에 직접 반납해도 되나요?','접수할 때 매장 직접 반납을 선택하실 수 있어요. 수거로 신청하셨다면 매장에 먼저 변경을 요청해 주세요.'],['오후타임 후에는 어디에서 기다리나요?','고객님과 약속한 반납 장소에서 장비와 함께 기다려 주세요. 장소가 헷갈리면 매장에 문의해 주세요.'],['빌린 장비가 맞지 않으면 어떻게 하나요?','매장에 연락해 장비 교환을 요청해 주세요. 현장에서 사이즈와 상태를 다시 확인해 드립니다.'],['이용 시간을 연장하고 싶어요.','반납 예정 전에 매장에 문의해 주세요. 재고와 다음 예약, 추가 요금을 확인한 뒤 안내해 드립니다.'],['리프트권은 어디에서 받나요?','접수 시 안내받은 수령 방법을 확인해 주세요. 대여 장비와 리프트권의 전달 상태는 따로 확인합니다.']];
 const places=[['만선 티롤 앞','티롤 호텔 정문 · 버스 정차 구역','약속한 차량을 확인한 뒤 장비를 전달해 주세요.'],['설천 주차장','접수 시 안내받은 만나는 위치','차량이 도착하면 담당 기사님과 위치를 확인해 주세요.'],['스키샵 직접 반납','장비를 받은 매장 카운터','카운터에서 장비 종류와 수량을 확인받아 주세요.']];
 const qrImg=()=>'<img class="so-qr-image" src="'+qr+'" alt="우리 스키샵 고객 이용 안내 페이지 QR 코드" width="232" height="232">';
 function render(){const t=S.state.tabs.guide||'qr';let body='';
  if(t==='qr')body='<div class="so-main-detail">'+panel('인쇄할 안내판','<div class="so-qr-sheet"><span class="so-guide-logo">'+icon('mountain-snow')+'우리 스키샵</span><h2>처음 오셨나요?</h2><p>이용 안내를 확인해 주세요</p>'+qrImg()+'<div class="so-guide-tags"><span>주차·방문</span><span>장비 반납</span><span>자주 묻는 질문</span></div><small>휴대폰 카메라로 QR을 비춰 주세요</small></div>')+panel('QR 안내 관리','<div class="so-panel-pad so-stack">'+status('체험용 안내 페이지','orange')+field('고객 안내 주소',url,'text','readonly')+'<p class="so-muted">주소를 유지하면 안내 내용을 바꿔도 기존 QR을 계속 쓸 수 있습니다.</p>'+link('손님 안내 화면 보기','guest-guide','','primary')+button('안내판 인쇄 미리보기','guide-print')+'<p class="so-note">아래 안내는 샘플입니다. 실제 매장 운영에 맞는 장소·시간·연락처로 바꾼 뒤 사용합니다.</p></div>')+'</div>';
  if(t==='content')body=panel('매장 기본 안내','<div class="so-panel-pad so-stack"><div class="so-form-grid">'+field('매장 이름','우리 스키샵')+field('문의 전화','010-0000-0000')+field('매장 주소','매장 주소를 등록하는 자리입니다')+field('주차 안내','매장 앞 안내받은 주차 구역을 이용해 주세요')+'</div><label class="so-field">고객에게 알릴 내용<textarea>접수한 수령·반납 장소와 시간을 확인해 주세요. 장비 교환이나 시간 변경은 매장에 먼저 문의해 주세요.</textarea></label>'+link('고객 화면 미리보기','guest-guide','','soft')+'</div>');
  if(t==='places')body=panel('반납 장소 안내','<div class="so-row-list">'+places.map(([name,detail,note],i)=>'<div class="so-row"><div><strong>'+name+'</strong><p class="so-muted">'+detail+'</p></div>'+button('안내 편집','guide-place',String(i),'small')+'</div>').join('')+'</div>');
  if(t==='faq')body=panel('자주 묻는 질문','<div class="so-row-list">'+faq.map(([question,answer],i)=>'<div class="so-row"><div><strong>'+question+'</strong><p class="so-muted">'+answer+'</p></div>'+button('질문 편집','guide-faq',String(i),'small')+'</div>').join('')+'</div>',button('질문 추가','guide-faq','new','small soft'));
  return head('QR 이용 안내','안내 페이지를 관리하고 카운터·차량에 둘 안내판을 확인하세요.',link('고객 화면 보기','guest-guide','','primary'))+S.tabs([['qr','QR·안내판'],['content','매장 안내'],['places','반납 장소'],['faq','자주 묻는 질문']],'qr')+body;
 }
 function guestGuide(){return '<div class="so-guest-shell"><header class="so-guest-brand">'+icon('mountain-snow')+'우리 스키샵<span>이용 안내 · 샘플</span></header><div class="so-guide-hero"><span class="so-eyebrow">WELCOME TO THE SLOPES</span><h1>장비를 받는 순간부터<br>반납까지 편안하게</h1><p>처음 방문하셔도 쉽게 이용하실 수 있도록<br>필요한 안내를 모았어요.</p></div><div class="so-guest-body"><nav class="so-guide-shortcuts" aria-label="안내 바로가기">'+[['visit','map-pin','방문 안내'],['return','package-check','반납 안내'],['faq','messages-square','자주 묻는 질문']].map(([id,glyph,label])=>'<button type="button" data-action="guide-jump" data-id="'+id+'">'+icon(glyph)+label+'</button>').join('')+'</nav><section id="so-guide-visit" class="so-stack"><h2>매장에 도착하면</h2><ol class="so-guide-steps"><li><span>1</span><div><strong>카운터에서 대표자 이름 확인</strong><p>예약·대여 내용을 확인해 주세요.</p></div></li><li><span>2</span><div><strong>장비와 사이즈 확인</strong><p>착용해 보고 불편한 곳이 없는지 알려주세요.</p></div></li><li><span>3</span><div><strong>수령·반납 약속 확인</strong><p>반납할 장소와 타임을 확인하면 준비 끝이에요.</p></div></li></ol><div class="so-actions">'+button(icon('phone')+'매장 연락처','guide-contact','','soft')+button(icon('map-pin')+'주차 안내','guide-parking')+'</div></section><section id="so-guide-return" class="so-stack"><h2>장비 반납 안내</h2><p class="so-muted">접수할 때 약속한 장소를 확인해 주세요.</p>'+places.map(([name,detail,note])=>'<article class="so-guide-place"><span>'+icon('map-pin')+'</span><div><h3>'+name+'</h3><p>'+detail+'</p><small>'+note+'</small></div></article>').join('')+'<p class="so-note">오후타임 후 · 야간타임 후 · 익일 오전<br>고객님 접수에 안내된 날짜와 타임을 기준으로 합니다.</p></section><section id="so-guide-faq" class="so-stack"><h2>자주 묻는 질문</h2><div class="so-faq">'+faq.map(([q,a])=>'<details><summary>'+q+'</summary><p>'+a+'</p></details>').join('')+'</div></section><section class="so-guide-help"><h2>방문 전 사이즈를 알려주세요</h2><p>일행의 장비를 미리 준비하는 데 도움이 돼요.</p>'+link('사이즈 입력 체험','guest-form','F-001','primary')+'</section><p class="so-preview-note">샘플 매장 안내입니다. 실제 예약·전화·문자와 연결되어 있지 않습니다.</p></div><footer>'+link('매장 화면 보기','guide','','quiet small')+'</footer></div>';}
 S.action('guide-print',()=>S.preview('안내판 인쇄 미리보기','<div class="so-qr-sheet compact"><span class="so-guide-logo">'+icon('mountain-snow')+'우리 스키샵</span><h2>이용 안내</h2>'+qrImg()+'<p>주차 · 반납 · 자주 묻는 질문</p><small>휴대폰 카메라로 QR을 비춰 주세요</small></div>'));
 S.action('guide-place',id=>{const p=places[Number(id)];S.preview('반납 장소 안내 편집',field('장소 이름',p[0])+field('만나는 위치',p[1])+field('고객 안내',p[2])+'<div class="so-photo-slot">'+icon('image')+'<span>현장 사진을 등록할 위치</span><small>정문·정차 구역이 보이는 사진을 사용합니다.</small></div>');});
 S.action('guide-faq',id=>{const item=faq[Number(id)]||['',''];S.preview(id==='new'?'자주 묻는 질문 추가':'자주 묻는 질문 편집',field('질문',item[0])+'<label class="so-field">답변<textarea>'+esc(item[1])+'</textarea></label><label class="so-check"><input type="checkbox" checked>고객 안내에 표시</label>');});
 S.action('guide-jump',id=>S.$('#so-guide-'+id)?.scrollIntoView({block:'start'}));
 S.action('guide-contact',()=>S.preview('매장 연락처','<h2>010-0000-0000</h2><p>전화번호 표시 예시입니다. 실제 통화는 시작하지 않습니다.</p>'));
 S.action('guide-parking',()=>S.preview('주차·방문 안내','<p>매장 앞 안내받은 주차 구역을 이용해 주세요.</p><p class="so-muted">실제 매장의 주소·주차 사진·지도 링크를 등록할 화면입니다.</p>'));
 S.register('guide',{title:'QR 이용 안내',render});S.register('guest-guide',{title:'고객 이용 안내',public:true,render:guestGuide});
})();
