(() => {
 const S=window.SkiOps,{icon,button,link,field}=S;
 S.state.authenticated=false;
 function render(){return '<div class="so-login-shell"><section class="so-login-story"><div class="so-login-brand"><span>'+icon('mountain-snow')+'</span><strong>우리 스키샵</strong></div><div class="so-login-copy"><span class="so-eyebrow">SKI RENT OPS</span><h1>우리 매장의 하루를,<br>조금 더 편하게.</h1><p>카운터와 차량이 같은 내용을 보고<br>편하게 일할 수 있도록.</p><div class="so-login-mini"><div class="so-login-mini-head"><strong>오늘의 업무</strong><span>카운터 · 차량</span></div><div><span class="so-login-mini-icon orange">' + icon('package-check') + ' </span><span><b>대여 장비 준비</b><small>고객별 이용일과 사이즈 확인</small></span><em>준비 중</em></div><div><span class="so-login-mini-icon purple">' + icon('truck') + '</span><span><b>배달·수거 일정</b><small>카운터와 차량에서 함께 확인</small></span><em>예정</em></div><div><span class="so-login-mini-icon green">' + icon('clipboard-check') + '</span><span><b>반납 확인과 하루 마감</b><small>장비와 금액을 빠짐없이</small></span><em>확인</em></div></div><div class="so-login-features"><div>'+icon('clipboard-list')+'대여·반납 현황</div><div>'+icon('handshake')+'거래처 정산</div><div>'+icon('list-checks')+'방문 전 장비 준비</div></div></div><small>우리 매장에 맞춰 살펴보는 운영 화면 시안</small></section><section class="so-login-form"><div class="so-login-form-inner"><span class="so-demo-label">화면 체험</span><h2>로그인</h2><p class="so-muted">사용할 화면을 선택해 주세요.</p><div class="so-stack">'+field('매장','우리 스키샵','text','readonly')+field('체험 계정','카운터 · 관리자','text','readonly')+'</div>'+button(icon('monitor')+'매장 POS로 들어가기','login-shop','','primary')+button(icon('tablet')+'차량 화면으로 들어가기','login-vehicle','','vehicle')+'<p class="so-login-note">비밀번호 없이 둘러볼 수 있어요.<br>실제 로그인·저장·문자 발송은 실행하지 않습니다.</p><div class="so-login-guest"><span>손님이 보는 화면도 확인해 보세요</span><div class="so-actions">'+link('사이즈 입력폼','guest-form','F-001','quiet small')+link('QR 이용 안내','guest-guide','','quiet small')+'</div></div></div></section></div>';}
 S.action('login-shop',()=>{S.state.authenticated=true;const target=S.state.afterLogin;S.state.afterLogin=null;S.go(target?.page||'home',target?.params||{},true);});
 S.action('login-vehicle',()=>{S.state.authenticated=true;S.state.afterLogin=null;S.go('vehicle',{},true);});
 S.action('logout',()=>{S.state.authenticated=false;S.state.afterLogin=null;S.state.history=[];S.state.guest=null;S.go('login',{},true);});
 S.register('login',{title:'로그인',public:true,entry:true,render});
})();
