(() => {
 const S=window.SkiOps,{head,panel,button,link,status,money,date,field,select,esc}=S;
 const partners=[{id:'P-001',name:'A스키샵',person:'김사장',phone:'010-0000-1001',note:'다음 날 오전 정산',get:100000,pay:400000,back:5,give:0},{id:'P-002',name:'B스키샵',person:'이사장',phone:'010-0000-1002',note:'장비 반환 수량 확인',get:0,pay:0,back:0,give:2},{id:'P-003',name:'서린스키',person:'박사장',phone:'010-0000-1003',note:'주말 거래 일괄 정산',get:80000,pay:0,back:0,give:0}];
 const trades=[{id:'T-001',partner:'P-001',kind:'리프트권 사오기',name:'오후권 성인 20매',price:30000,qty:20,days:1,amount:600000,paid:200000,direction:'pay',gear:0,returned:0},{id:'T-002',partner:'P-001',kind:'장비 빌려주기',name:'스키 5대 · 2일',price:10000,qty:5,days:2,amount:100000,paid:0,direction:'get',gear:5,returned:0},{id:'T-003',partner:'P-002',kind:'장비 빌려오기',name:'스키 5대 · 2일',price:8000,qty:5,days:2,amount:80000,paid:80000,direction:'pay',gear:5,returned:3},{id:'T-004',partner:'P-003',kind:'리프트권 팔기',name:'야간권 성인 6매',price:30000,qty:6,days:1,amount:180000,paid:100000,direction:'get',gear:0,returned:0}];
 S.data.partners=partners;S.data.trades=trades;
 const selected=()=>partners.find(p=>p.id===S.state.params.id)||partners[0];
 const metric=(label,n,unit='원',color='')=>'<div class="so-metric '+color+'"><span class="so-metric-label">'+label+'</span><strong>'+Number(n).toLocaleString('ko-KR')+'<em>'+unit+'</em></strong></div>';
 function partnerRows(q=''){const list=partners.filter(p=>(p.name+' '+p.person+' '+p.phone).includes(q.trim()));return list.length?list.map(p=>'<tr><td><button type="button" class="so-text-button" data-go="partner" data-id="'+p.id+'"><strong>'+p.name+'</strong><small>'+p.person+' · '+p.phone+'</small></button></td><td data-label="받을 돈"><strong class="'+(p.get?'so-receivable':'so-zero')+'">'+money(p.get)+'</strong></td><td data-label="줄 돈"><strong class="'+(p.pay?'so-payable':'so-zero')+'">'+money(p.pay)+'</strong></td><td data-label="장비 반환">'+(p.back?status('돌려받을 '+p.back+'대','orange'):p.give?status('돌려줄 '+p.give+'대','purple'):'없음')+'</td><td data-label="메모">'+p.note+'</td><td>'+link('내역','partner',p.id,'small')+'</td></tr>').join(''):'<tr><td colspan="6"><p class="so-empty">검색한 거래처가 없습니다.</p></td></tr>';}
 function list(){return head('거래처 장부','타 매장과 주고받은 돈과 장비를 구분해서 확인하세요.',button('거래처 등록','partner-create','','')+button('새 거래 등록','partner-new','','primary'))+'<div class="so-metrics">'+metric('받을 돈',180000,'원','receivable')+metric('줄 돈',400000,'원','accent')+metric('돌려받을 장비',5,'대')+metric('돌려줄 장비',2,'대')+'</div><div class="so-filter-panel"><div class="so-toolbar"><label class="so-field so-search">거래처 찾기<input type="search" data-search="partners" placeholder="업체명, 담당자 또는 연락처"></label><span class="so-search-hint">돈 정산과 장비 반환을 각각 확인하세요.</span></div></div>'+panel('거래처별 잔액','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>거래처</th><th>받을 돈</th><th>줄 돈</th><th>장비 반환</th><th>정산 메모</th><th></th></tr></thead><tbody id="so-partner-rows">'+partnerRows()+'</tbody></table></div>')+'<p class="so-preview-note">돈 정산과 장비 반환은 별도로 확인합니다. 샘플 장부입니다.</p>';}
 S.search('partners',q=>{S.$('#so-partner-rows').innerHTML=partnerRows(q);});
 function tradeRows(p){return trades.filter(t=>t.partner===p.id).map(t=>'<tr><td><strong>'+t.kind+'</strong><small>'+t.id+' · '+date(S.data.today)+'</small></td><td>'+t.name+'<small>'+money(t.price)+' × '+t.qty+(t.days>1?' × '+t.days+'일':'')+'</small></td><td data-label="거래 금액">'+money(t.amount)+'</td><td data-label="남은 돈">'+status(t.direction==='get'?'받을 돈':'줄 돈',t.direction==='get'?'blue':'orange')+'<strong>'+money(t.amount-t.paid)+'</strong></td><td>'+button('거래 상세','partner-trade',t.id,'small')+'</td></tr>').join('');}
 function detail(){const p=selected(),tab=S.state.tabs.partner||'trades';let body='';
  if(tab==='trades')body=panel('거래 내역','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>거래 종류</th><th>품목·수량</th><th>거래 금액</th><th>미정산</th><th></th></tr></thead><tbody>'+tradeRows(p)+'</tbody></table></div>');
  if(tab==='settlements')body=panel('정산 내역','<div class="so-panel-pad so-stack">'+trades.filter(t=>t.partner===p.id&&t.paid).map(t=>'<div class="so-row"><div><strong>'+t.id+' · '+(t.direction==='pay'?'돈 지급':'돈 받음')+'</strong><p class="so-muted">'+date(S.data.today)+' · 계좌이체 · 샘플 정산</p></div><strong>'+money(t.paid)+'</strong></div>').join('')+'<div class="so-actions">'+button('돈 받음','partner-receive',p.id,'primary')+button('돈 지급','partner-pay',p.id)+button('상계 화면','partner-offset',p.id)+'</div><p class="so-muted">상계는 실제 돈 이동과 구분해서 기록합니다.</p></div>');
  if(tab==='equipment')body=panel('장비 반환 내역','<div class="so-panel-pad so-stack">'+(trades.filter(t=>t.partner===p.id&&t.gear).map(t=>'<div class="so-row"><div><strong>'+t.kind+' · '+t.gear+'대</strong><p class="so-muted">'+t.returned+'대 반환 확인 · '+(t.gear-t.returned)+'대 남음</p></div>'+button('반환 확인 화면','partner-return',t.id,'soft')+'</div>').join('')||'<p class="so-empty">장비 대차 내역이 없습니다.</p>')+'</div>');
  return head(p.name,p.person+' · '+p.phone,button('목록으로','back'),'거래처 상세')+'<div class="so-metrics">'+metric('받을 돈',p.get)+metric('줄 돈',p.pay,'원','accent')+metric('돌려받을 장비',p.back,'대')+metric('돌려줄 장비',p.give,'대')+'</div><div class="so-toolbar">'+S.tabs([['trades','거래 내역'],['settlements','정산 내역'],['equipment','장비 반환']],'trades')+'<div class="so-actions">'+button('거래명세서','partner-statement',p.id)+button('새 거래','partner-new',p.id,'primary')+'</div></div>'+body;
 }
 S.action('partner-create',()=>S.preview('거래처 등록','<div class="so-form-grid">'+field('업체명','')+field('담당자','')+field('연락처','','tel')+field('정산 메모','')+'</div>'));
 S.action('partner-new',id=>{S.modal('새 거래 등록',select('거래처',partners.map(p=>[p.id,p.name]),id||'P-001','data-trade-partner')+'<div class="so-grid2">'+[['ticket-buy','리프트권 사오기'],['ticket-sell','리프트권 팔기'],['gear-in','장비 빌려오기'],['gear-out','장비 빌려주기']].map(([kind,label])=>button(label,'partner-kind',kind,'soft')).join('')+'</div><p class="so-muted">거래 종류를 선택하면 필요한 입력 항목을 보여줍니다.</p>');});
 S.action('partner-kind',kind=>{const partner=S.$('[data-trade-partner]')?.value||'P-001';const ticket=kind.startsWith('ticket'),incoming=['ticket-buy','gear-in'].includes(kind);const labels={'ticket-buy':'리프트권 사오기','ticket-sell':'리프트권 팔기','gear-in':'장비 빌려오기','gear-out':'장비 빌려주기'};S.modal(labels[kind],'<p>'+partners.find(p=>p.id===partner).name+' · '+status(incoming?'우리가 줄 돈':'우리가 받을 돈',incoming?'orange':'blue')+'</p><div class="so-form-grid">'+select(ticket?'권종':'장비 종류',ticket?['오후권 · 성인','야간권 · 성인','후야권 · 성인','오후권 · 소인']:['스키 · 일반','스키 · 고급','보드 · 일반','의류'])+field(ticket?'매수':'실제 장비 수량',ticket?20:5,'number','min="1"')+field(ticket?'사용 날짜':'이용 시작일',S.data.today,'date')+field(ticket?'정산 예정일':'이용 종료일',S.data.day(1),'date')+field(ticket?'1매 단가':'1개 · 1일 단가',ticket?30000:10000,'number','min="0"')+select('정산 상태',['아직 정산 안 함','일부 정산','전액 정산'])+'</div>'+field('메모','')+S.previewNote+'<div class="so-dialog-actions">'+button('닫기','close')+'</div>');});
 S.action('partner-trade',id=>{const t=trades.find(t=>t.id===id);S.preview(t.kind+' 상세','<p>'+t.id+' · '+t.name+'</p><div>'+[['거래 금액',t.amount],['이미 정산한 금액',t.paid],[t.direction==='pay'?'남은 줄 돈':'남은 받을 돈',t.amount-t.paid]].map(([l,n])=>'<div class="so-summary-line"><span>'+l+'</span><strong>'+money(n)+'</strong></div>').join('')+'</div>'+(t.gear?'<p class="so-note">장비 '+t.gear+'대 중 '+t.returned+'대 반환 · '+(t.gear-t.returned)+'대 남음</p>':''));});
 for(const a of ['partner-receive','partner-pay'])S.action(a,id=>{const p=partners.find(p=>p.id===id);S.preview(a==='partner-pay'?'업체에 돈 지급':'업체에서 돈 받음','<p><strong>'+p.name+'</strong></p><div class="so-form-grid">'+field('정산 금액',a==='partner-pay'?p.pay:p.get,'number','min="0"')+select('방법',['계좌이체','현금','카드'])+field('정산 날짜',S.data.today,'date')+field('메모','')+'</div><p class="so-muted">실제 받은 금액을 대상 거래에 배분하는 화면입니다.</p>');});
 S.action('partner-offset',id=>{const p=partners.find(p=>p.id===id),offset=Math.min(p.get,p.pay);S.preview('받을 돈 · 줄 돈 상계','<p><strong>'+p.name+'</strong> · 샘플 상계 미리보기</p><div>'+[['현재 받을 돈',p.get],['현재 줄 돈',p.pay],['상계할 금액',offset],['상계 후 받을 돈',p.get-offset],['상계 후 줄 돈',p.pay-offset]].map(([l,n])=>'<div class="so-summary-line"><span>'+l+'</span><strong>'+money(n)+'</strong></div>').join('')+'</div><p class="so-note">실제 현금 이동 0원 · 장비 반환 의무는 그대로 남습니다.</p>');});
 S.action('partner-return',id=>{const t=trades.find(t=>t.id===id);S.preview('장비 반환 확인','<p>'+t.kind+' · '+t.name+'</p><div class="so-summary-line"><span>아직 반환하지 않은 수량</span><strong>'+(t.gear-t.returned)+'대</strong></div>'+field('이번에 반환 확인할 수량',t.gear-t.returned,'number','min="0" max="'+(t.gear-t.returned)+'"')+field('확인 메모','')+'<p class="so-muted">반환 확인과 돈 정산은 별개입니다.</p>');});
 S.action('partner-statement',id=>{const p=partners.find(p=>p.id===id);S.preview('거래명세서 미리보기','<p>우리 스키샵 ↔ <strong>'+p.name+'</strong> · '+date(S.data.today)+'</p><div class="so-table-wrap"><table><thead><tr><th>품목</th><th>금액</th></tr></thead><tbody>'+trades.filter(t=>t.partner===id).map(t=>'<tr><td>'+t.kind+'<small>'+t.name+'</small></td><td>'+money(t.amount)+'</td></tr>').join('')+'</tbody></table></div><div class="so-summary-line"><span>받을 돈 / 줄 돈</span><strong>'+money(p.get)+' / '+money(p.pay)+'</strong></div>');});
 S.register('partners',{title:'거래처 장부',render:list});S.register('partner',{title:'거래처 상세',parent:'partners',render:detail});
})();
