(() => {
 const S=window.SkiOps,{head,panel,button,link,status,money,date,field,select,esc,icon}=S;
 const requests=[{id:'F-001',order:'R-027',name:'윤서준',phone:'010-0000-0027',count:2,replies:2,pickup:S.data.today,time:'18:00',start:S.data.day(1),end:S.data.day(2),status:'제출 완료',color:'green',prep:'준비 중',people:[{name:'윤서준',height:'175',shoe:'260',gear:'스키',clothes:'L',days:[true,true]},{name:'일행 2',height:'162',shoe:'240',gear:'스키',clothes:'M',days:[true,true]}]},{id:'F-002',order:'R-022',name:'박준호',phone:'010-0000-0022',count:3,replies:2,pickup:S.data.today,time:'16:40',start:S.data.today,end:S.data.today,status:'일부 제출',color:'orange',prep:'확인 필요',people:[{name:'박준호',height:'178',shoe:'270',gear:'스키',clothes:'없음',days:[true]},{name:'일행 2',height:'165',shoe:'245',gear:'보드',clothes:'없음',days:[true]}]},{id:'F-003',order:'R-025',name:'김민수',phone:'010-0000-0025',count:4,replies:4,pickup:S.data.today,time:'09:20',start:S.data.today,end:S.data.day(1),status:'변경됨',color:'purple',prep:'변경 확인',people:[{name:'김민수',height:'175',shoe:'260',gear:'스키',clothes:'없음',days:[true,true]},{name:'일행 2',height:'168',shoe:'250',gear:'스키',clothes:'없음',days:[true,true]},{name:'일행 3',height:'162',shoe:'240',gear:'스키',clothes:'없음',days:[true,true]},{name:'일행 4',height:'170',shoe:'255',gear:'스키',clothes:'없음',days:[true,false]}]}];
 S.data.requests=requests;
 const req=id=>requests.find(r=>r.id===id)||requests[0];
 const datesFor=(start,end)=>{const count=Math.round((Date.parse(end+'T00:00:00Z')-Date.parse(start+'T00:00:00Z'))/86400000)+1;return Number.isFinite(count)&&count>0&&count<=31?Array.from({length:count},(_,i)=>new Date(Date.parse(start+'T00:00:00Z')+i*86400000).toISOString().slice(0,10)):[];};
 function rows(list){return list.length?list.map(r=>'<tr><td><strong>'+r.name+'</strong><small>'+r.phone+' · '+r.order+'</small></td><td data-label="수령일"><strong>'+date(r.pickup)+' '+r.time+'</strong><small>장비를 받는 날</small></td><td data-label="이용일">'+date(r.start)+' ~ '+date(r.end)+'<small>'+datesFor(r.start,r.end).map((d,i)=>date(d)+' '+r.people.filter(p=>p.days[i]).length+'명').join(' · ')+'</small></td><td data-label="응답"><strong>'+r.replies+' / '+r.count+'명</strong>'+(r.replies<r.count?'<small class="so-stock-low">'+(r.count-r.replies)+'명 미입력</small>':'<small>모두 입력했어요</small>')+'</td><td>'+status(r.status,r.color)+'<small>'+r.prep+'</small></td><td><div class="so-actions">'+link('응답 확인','response',r.id,'small')+button('발송 화면','form-send',r.id,'small quiet')+'</div></td></tr>').join(''):'<tr><td colspan="6"><p class="so-empty">해당 조건의 요청이 없습니다.</p></td></tr>';}
 function filteredRequests(){const q=(S.state.filters.prepQuery||'').trim(),v=S.state.filters.prepStatus||'all';return requests.filter(r=>r.name.includes(q)&&(v==='all'||v==='complete'&&r.status==='제출 완료'||v==='pending'&&r.status!=='제출 완료'));}
 function list(){const t=S.state.tabs.preparation||'requests';let body='';
  if(t==='requests')body='<div class="so-filter-panel"><div class="so-toolbar"><label class="so-field so-search">대표자 찾기<input type="search" data-search="prep-request" placeholder="이름으로 검색" value="'+esc(S.state.filters.prepQuery||'')+'"></label>'+select('제출 상태',[['all','전체'],['pending','확인 필요'],['complete','제출 완료']],S.state.filters.prepStatus||'all','data-change="prep-status"')+button(icon('rotate-ccw')+'초기화','prep-reset','','quiet')+'</div></div>'+panel('입력 요청 목록','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>대표자 / 예약</th><th>수령 예정</th><th>이용일 · 일별 인원</th><th>제출 인원</th><th>입력·준비 상태</th><th></th></tr></thead><tbody id="so-request-rows">'+rows(filteredRequests())+'</tbody></table></div>');
  if(t==='ready')body='<div class="so-note" style="margin-bottom:16px">수령 예정일 기준 준비표입니다. 오늘 받아 내일부터 타는 손님도 포함합니다.</div>'+panel('오늘 준비할 장비','<div class="so-row-list">'+requests.filter(r=>r.order!=='R-025').map(r=>'<div class="so-row"><div><strong>'+r.time+' · '+r.name+'</strong><p class="so-muted">이용 '+date(r.start)+' ~ '+date(r.end)+' · '+r.people.map(p=>p.gear+' / '+p.shoe+'mm'+(p.clothes!=='없음'?' / 의류 '+p.clothes:'')).join(' · ')+'</p></div><div class="so-actions">'+status(r.prep,r.color)+link('준비 상세','response',r.id,'small')+'</div></div>').join('')+'</div>')+'<div class="so-grid2" style="margin-top:18px">'+panel('사이즈별 준비 요약','<div class="so-panel-pad so-counts"><span class="so-count">스키 부츠 260mm<strong>1</strong></span><span class="so-count">스키 부츠 240mm<strong>1</strong></span><span class="so-count">스키 부츠 270mm<strong>1</strong></span><span class="so-count">보드 부츠 245mm<strong>1</strong></span></div>')+panel('확인할 항목','<div class="so-panel-pad"><strong>박준호 · 일행 1명 미입력</strong><p class="so-muted">예약 장비 3개, 현재 입력 2명 · 현장 확인 필요</p></div>')+'</div>';
  if(t==='template')body=panel('고객에게 받을 정보','<div class="so-panel-pad so-stack"><p class="so-muted">익숙한 질문을 켜고 끄며 구성합니다.</p>'+[['일행 표시명',true],['필요 장비',true],['이용 날짜',true],['키 (cm)',true],['발 사이즈 (mm)',true],['의류 사이즈',false],['헬멧 사이즈',false],['요청 메모',false]].map(([name,required])=>'<div class="so-row"><strong>'+name+'</strong><div class="so-actions"><label class="so-check"><input type="checkbox" checked>표시</label><label class="so-check"><input type="checkbox" '+(required?'checked':'')+'>필수</label></div></div>').join('')+'<p class="so-note">사이즈를 모르는 손님은 현장 확인을 선택할 수 있게 합니다.</p>'+link('손님 화면 미리보기','guest-form','F-001','primary')+'</div>');
  return head('사전 입력·준비','방문 전에 사이즈를 받고, 수령일별로 장비를 준비하세요.',button('입력폼 보내기','form-send','F-001','primary'))+S.tabs([['requests','발송·응답 관리'],['ready','날짜별 준비표'],['template','입력폼 설정']],'requests')+body;
 }
 S.action('prep-reset',()=>{S.state.filters.prepQuery='';S.state.filters.prepStatus='all';S.render();});
 S.search('prep-request',q=>{S.state.filters.prepQuery=q;S.$('#so-request-rows').innerHTML=rows(filteredRequests());});
 S.change('prep-status',v=>{S.state.filters.prepStatus=v;S.$('#so-request-rows').innerHTML=rows(filteredRequests());});
 function response(){const r=req(S.state.params.id);return head(r.name+' · 사전 입력',r.order+' / '+r.phone,button('목록으로','back'),'응답·준비 상세')+'<div class="so-toolbar"><div class="so-actions">'+status(r.status,r.color)+'<strong>'+r.replies+' / '+r.count+'명 제출</strong></div><div class="so-actions">'+link('연결된 대여','rental',r.order)+link('손님 화면 보기','guest-form',r.id,'soft')+'</div></div>'+(r.status==='변경됨'?'<div class="so-note" style="margin-bottom:16px">일행 4의 이용일이 첫날만 이용으로 변경되었습니다. 기존 접수에 자동 반영하지 않습니다.</div>':'')+'<div class="so-main-detail">'+panel('일행별 사이즈','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>일행</th><th>필요 장비</th><th>키 / 발 사이즈</th><th>이용일</th><th>준비</th></tr></thead><tbody>'+r.people.map((p,i)=>'<tr><td><strong>'+p.name+'</strong></td><td>'+p.gear+(p.clothes!=='없음'?' · 의류 '+p.clothes:'')+'</td><td>'+p.height+'cm / '+p.shoe+'mm</td><td>'+p.days.map((used,j)=>used?date(datesFor(r.start,r.end)[j]):'').filter(Boolean).join(', ')+'</td><td>'+button('피팅·준비','prep-person',r.id+':'+i,'small')+'</td></tr>').join('')+'</tbody></table></div>')+panel('준비 요약','<div class="so-panel-pad so-stack"><div><p class="so-muted">장비를 받는 날</p><h2>'+date(r.pickup)+' '+r.time+'</h2></div><div><p class="so-muted">실제 이용일</p><strong>'+date(r.start)+' ~ '+date(r.end)+'</strong></div><div class="so-counts">'+datesFor(r.start,r.end).map((d,i)=>'<span class="so-count">'+(i+1)+'일차<strong>'+r.people.filter(p=>p.days[i]).length+'명</strong></span>').join('')+'</div><p class="so-note">'+(r.replies<r.count?'미입력 일행 '+(r.count-r.replies)+'명 · 수량 확인 필요':'입력 사이즈와 실제 지급 사이즈는 현장에서 확인합니다.')+'</p>'+button('발송 내용 확인','form-send',r.id)+'</div>')+'</div>';}
 S.action('form-send',id=>{const r=req(id);S.modal('사이즈 입력폼 발송',select('연결할 고객·예약',requests.map(r=>[r.id,r.name+' · '+r.order]),r.id,'data-change="send-customer"')+'<div id="so-form-send-preview">'+sendBody(r)+'</div>'+S.previewNote);});
 function sendBody(r){return '<div class="so-stack"><p>'+r.phone+' · '+date(r.start)+' ~ '+date(r.end)+' 이용</p><div class="so-note">[우리 스키샵] 방문 전 일행별 키·발 사이즈·필요 장비를 입력해 주세요. 장비를 미리 준비하는 데 도움이 됩니다.</div>'+field('체험용 입력 링크','https://rosookwan.github.io/ski-rent-ops/?view=guest-form','text','readonly')+'<div class="so-dialog-actions">'+button('닫기','close')+link('손님 화면 보기','guest-form',r.id,'primary')+'</div></div>';}
 S.change('send-customer',id=>{S.$('#so-form-send-preview').innerHTML=sendBody(req(id));});
 S.action('prep-person',value=>{const [id,index]=value.split(':'),r=req(id),p=r.people[Number(index)];S.preview(p.name+' · 피팅·준비','<p>요청: '+p.gear+' · '+p.shoe+'mm'+(p.clothes!=='없음'?' · 의류 '+p.clothes:'')+'</p><div class="so-form-grid">'+field('실제 지급 부츠 (mm)',p.shoe,'number')+select('준비 상태',['미준비','준비 중','준비 완료','현장 확인'])+field('장비 메모','')+'</div><p class="so-muted">준비 완료와 실제 지급 완료를 구분하는 화면입니다.</p>');});
 function guestState(){const id=S.state.params.id||'F-001';if(!S.state.guest||S.state.guest.id!==id){const r=req(id);S.state.guest={id,step:1,name:r.name,start:r.start,end:r.end,people:r.people.map(p=>({...p,days:[...p.days]}))};}return S.state.guest;}
 function capturePeople(){const g=guestState();S.root.querySelectorAll('[data-person-card]').forEach(card=>{const p=g.people[Number(card.dataset.personCard)];for(const key of ['name','height','shoe','gear','clothes'])p[key]=card.querySelector('[data-person-field="'+key+'"]'+(key==='gear'?':checked':''))?.value??p[key];p.days=[...card.querySelectorAll('[data-person-day]')].map(c=>c.checked);});}
 function personCard(p,i,dates){
  return '<section class="so-person-card" data-person-card="'+i+'"><div class="so-panel-head"><h2>일행 '+(i+1)+'</h2>'+(guestState().people.length>1?button('삭제','guest-remove',String(i),'quiet small'):'')+'</div><div class="so-panel-pad so-stack">'+field('이름 또는 구분',p.name,'text','data-person-field="name"')+
    '<fieldset class="so-gear-choice"><legend>필요 장비</legend><div>'+['스키','보드','장비 없음'].map(gear=>'<label><input type="radio" name="gear-'+i+'" data-person-field="gear" value="'+gear+'" '+(p.gear===gear?'checked':'')+'><span>'+gear+'</span></label>').join('')+'</div></fieldset>'+
    '<div class="so-form-grid">'+field('키 (cm)',p.height,'number','data-person-field="height" min="50" max="230" placeholder="예: 170" '+(!p.height?'disabled':''))+button('키를 몰라요 · 현장 확인','guest-height-unknown',String(i),'quiet small')+select('발 사이즈 (mm)',['현장 확인',...Array.from({length:29},(_,n)=>String(160+n*5))],p.shoe,'data-person-field="shoe"')+select('의류 사이즈',['없음','XS','S','M','L','XL','현장 확인'],p.clothes,'data-person-field="clothes"')+'</div><div class="so-use-days"><span>이용할 날짜</span><div aria-label="일행 '+(i+1)+' 이용일">'+dates.map((useDate,j)=>'<label class="so-check"><input type="checkbox" data-person-day="'+j+'" '+(p.days[j]?'checked':'')+'>'+date(useDate)+' 이용</label>').join('')+'</div></div></div></section>';
 }
 function guest(){
  const g=guestState(),guestDates=datesFor(g.start,g.end),stepNames=['방문 정보','일행 정보','내용 확인','입력 완료'];let body='',actions='';
  if(g.step===1){
   body='<h1>방문 전에<br>사이즈를 알려주세요</h1><p class="so-guest-description">일행의 장비를 미리 준비할게요.<br>모르는 사이즈는 현장에서 확인할 수 있어요.</p><div class="so-stack">'+field('대표자 이름',g.name,'text','data-guest-name')+'<div class="so-form-grid">'+field('이용 시작일',g.start,'date','data-guest-start')+field('이용 종료일',g.end,'date','data-guest-end')+'</div></div><p class="so-muted">예약·결제가 확정되는 화면은 아닙니다.</p>';
   actions=button('일행 정보 입력하기 '+icon('arrow-right'),'guest-next','','primary');
  }
  if(g.step===2){
   body='<h1>누가 함께 타나요?</h1><p class="so-guest-description">일행별로 필요한 장비와 사이즈를 선택해 주세요.</p><div class="so-stack">'+g.people.map((p,i)=>personCard(p,i,guestDates)).join('')+'</div>'+button(icon('plus')+'일행 추가','guest-add','','soft');
   actions=button('이전','guest-prev')+button('입력 내용 확인','guest-next','','primary');
  }
  if(g.step===3){
   body='<h1>입력 내용을<br>확인해 주세요</h1><p class="so-guest-description">'+esc(g.name)+' · '+date(g.start)+' ~ '+date(g.end)+'</p><div class="so-review-people">'+g.people.map(p=>'<article><strong>'+esc(p.name)+'</strong><p>'+esc(p.gear)+(p.clothes!=='없음'?' · 의류 '+esc(p.clothes):'')+'</p><p class="so-muted">'+(p.shoe==='현장 확인'?'발 사이즈 현장 확인':esc(p.shoe)+'mm')+' · '+(p.height?esc(p.height)+'cm':'키 현장 확인')+'</p><span>'+p.days.map((v,j)=>v?date(guestDates[j]):'').filter(Boolean).join(' / ')+' 이용</span></article>').join('')+'</div><div class="so-note">입력한 정보는 장비 준비에 참고합니다. 실제 지급 장비는 현장에서 확인해 주세요.</div>';
   actions=button('수정하기','guest-prev')+button('제출 화면 미리보기','guest-next','','primary');
  }
  if(g.step===4){
   body='<div class="so-guest-finish"><span class="so-success-mark">'+icon('check')+'</span><h1>입력 내용을 확인했어요</h1><p>폼 입력을 마쳤을 때의 화면입니다.</p><p class="so-muted">체험용으로, 매장에 실제 전송되지는 않았습니다.</p></div>';
   actions=link('이용 안내 보기','guest-guide','','primary');
  }
  return '<div class="so-guest-shell"><header class="so-guest-brand">'+icon('mountain-snow')+'우리 스키샵<span>사전 사이즈 입력</span></header><div class="so-guest-step"><span>'+stepNames[g.step-1]+'</span><b>'+g.step+' / 4</b></div><div class="so-guest-progress" aria-label="'+g.step+' / 4단계">'+[1,2,3,4].map(n=>'<span class="'+(n<=g.step?'active':'')+'"></span>').join('')+'</div><div class="so-guest-body">'+body+'</div><footer><p class="so-guest-error" id="so-guest-error" role="alert" hidden></p><div class="so-guest-footer-actions">'+actions+'</div>'+link('카운터 화면 보기','preparation','','quiet small')+'</footer></div>';
 }
 S.action('guest-height-unknown',(i,b)=>{const input=S.$('[data-person-card="'+i+'"] [data-person-field="height"]');input.disabled=!input.disabled;if(input.disabled)input.value='';else input.focus();b.setAttribute('aria-pressed',String(input.disabled));b.textContent=input.disabled?'키 직접 입력하기':'키를 몰라요 · 현장 확인';});
 S.action('guest-next',()=>{const g=guestState();if(g.step===1){const name=S.$('[data-guest-name]').value.trim(),start=S.$('[data-guest-start]').value,end=S.$('[data-guest-end]').value;if(!name||!datesFor(start,end).length){const e=S.$('#so-guest-error');e.hidden=false;e.textContent='대표자와 1~31일 이내의 이용 날짜를 입력해 주세요.';return;}g.name=name;g.start=start;g.end=end;g.people.forEach(p=>p.days=datesFor(start,end).map((_,i)=>p.days[i]??true));}if(g.step===2){capturePeople();if(g.people.some(p=>!p.name.trim()||!p.days.some(Boolean))){const e=S.$('#so-guest-error');e.hidden=false;e.textContent='일행 이름과 이용할 날짜를 한 개 이상 선택해 주세요.';return;}}g.step=Math.min(4,g.step+1);S.render();});
 S.action('guest-prev',()=>{const g=guestState();if(g.step===2)capturePeople();g.step=Math.max(1,g.step-1);S.render();});S.action('guest-add',()=>{capturePeople();const g=guestState();g.people.push({name:'일행 '+(g.people.length+1),height:'',shoe:'현장 확인',gear:'스키',clothes:'없음',days:datesFor(g.start,g.end).map(()=>true)});S.render();});S.action('guest-remove',i=>{capturePeople();const g=guestState();if(g.people.length>1)g.people.splice(Number(i),1);S.render();});
 S.register('preparation',{title:'사전 입력·준비',render:list});S.register('response',{title:'응답·준비 상세',parent:'preparation',render:response});S.register('guest-form',{title:'사전 사이즈 입력',public:true,render:guest});
})();
