(() => {
  const S=window.SkiOps,{head,panel,button,link,status,money,date,icon,field,select,esc}=S;
  const orders=S.data.orders, selected=()=>orders.find(o=>o.id===S.state.params.id)||orders[0];
  const tab=()=>S.state.tabs[S.state.page]||'all';
  const metric=(label,value,hint,page='rentals',accent='')=>'<button type="button" class="so-metric '+accent+'" data-go="'+page+'"><span class="so-metric-label">'+label+'</span><strong>'+value+'</strong><small>'+hint+'</small></button>';
  function rows(list){return list.length?list.map(o=>'<tr><td><button class="so-text-button" type="button" data-go="rental" data-id="'+o.id+'"><strong>'+o.name+'</strong><small>'+o.id+' · '+o.phone+'</small></button></td><td data-label="이용 기간">'+date(o.start)+(o.start!==o.end?' ~ '+date(o.end):'')+'<small>'+o.detail+'</small></td><td data-label="장비">'+o.gear+'<small>'+(o.issued?'지급 '+o.issued+' · 매장 확인 '+o.returned:'지급 전')+'</small></td><td data-label="반납 예정">'+date(o.due)+' · '+o.slot+'<small>'+o.method+' · '+o.place+'</small></td><td data-label="받을 돈"><strong class="so-money '+(o.amount>o.paid?'is-due':'')+'">'+money(o.amount-o.paid)+'</strong>'+status(o.status,o.color)+'</td><td>'+link('상세','rental',o.id,'small')+'</td></tr>').join(''):'<tr><td colspan="6"><p class="so-empty">조건에 맞는 대여가 없습니다.</p></td></tr>';}
  function filtered(){const q=(S.state.filters.rentalQuery||'').replace(/[\s-]/g,'');const d=S.state.filters.rentalDate||'all';return orders.filter(o=>(!q||[o.name,o.phone.replace(/-/g,''),o.id].some(v=>v.includes(q)))&&(tab()==='all'||(tab()==='out'&&o.status==='대여 중')||(tab()==='pickup'&&o.status==='수령 예정')||(tab()==='return'&&o.due===S.data.today&&o.issued>0)||(tab()==='check'&&o.status==='매장 확인 대기')||(tab()==='unpaid'&&o.amount>o.paid))&&(d==='all'||o.start<=d&&o.end>=d||o.pickup===d));}
  function table(list){return '<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>대표자 / 접수번호</th><th>이용 기간</th><th>실제 장비</th><th>반납 예정</th><th>미수 / 상태</th><th></th></tr></thead><tbody id="so-rental-rows">'+rows(list)+'</tbody></table></div>';}
  function rentalList(){
    const count=(label,n)=>label+'<span class="so-tab-count">'+n+'</span>';
    const tabs=[['all',count('전체',orders.length)],['pickup',count('수령 예정',orders.filter(o=>o.status==='수령 예정').length)],['out',count('대여 중',orders.filter(o=>o.status==='대여 중').length)],['return',count('오늘 반납',orders.filter(o=>o.due===S.data.today&&o.issued>0).length)],['check',count('매장 확인 대기',orders.filter(o=>o.status==='매장 확인 대기').length)],['unpaid',count('미수 있음',orders.filter(o=>o.amount>o.paid).length)]];
    return head('렌탈현황','예약부터 마지막 반납 확인까지, 고객별로 한눈에',link(icon('plus')+'새 대여 접수','intake','','primary'))+
      '<div class="so-filter-panel">'+S.tabs(tabs,'all')+'<div class="so-toolbar"><label class="so-field so-search">고객 찾기<input type="search" data-search="rentals" placeholder="이름, 연락처 또는 접수번호" value="'+esc(S.state.filters.rentalQuery||'')+'"></label>'+select('날짜',[['all','전체 이용일'],[S.data.today,'오늘'],[S.data.day(1),'내일']],S.state.filters.rentalDate||'all','data-change="rental-date"')+button(icon('rotate-ccw')+'초기화','rental-reset','','quiet')+'</div></div>'+panel('대여 목록',table(filtered()),'<span class="so-muted">샘플 접수 '+orders.length+'건</span>');
  }
  S.action('rental-reset',()=>{S.state.filters.rentalQuery='';S.state.filters.rentalDate='all';S.state.tabs.rentals='all';S.render();});
  S.search('rentals',q=>{S.state.filters.rentalQuery=q;S.$('#so-rental-rows').innerHTML=rows(filtered());S.icons();});
  S.change('rental-date',v=>{S.state.filters.rentalDate=v;S.render();});
  function home(){
    const totalDue=orders.reduce((n,o)=>n+o.amount-o.paid,0);
    const tasks=[['최은정','수거한 장비 최종 확인','수거 완료','R-024','매장 확인','purple'],['박준호','설천 주차장 · 장비 배달','16:40','R-022','배달 예정','blue'],['정하늘','오후권 성인 4매 전달','17:30','R-026','리프트권','orange'],['윤서준','내일부터 이틀 이용 · 장비 준비','18:00','R-027','매장 수령','green']];
    const stats=[['수령 예정','2','팀','오늘 장비를 받는 고객','package-check','orange','rentals'],['대여 중','3','팀','현재 이용 중인 고객','snowflake','blue','rentals'],['매장 확인 대기','1','팀','수거 후 수량 확인이 필요해요','clipboard-check','purple','rentals'],['고객 미수금',totalDue.toLocaleString('ko-KR'),'원','대여금액에서 받은 금액을 제외','wallet','green','closing']];
    return head('오늘의 매장','반가워요. 오늘의 대여와 반납 일정을 확인해 주세요.',link(icon('plus')+'새 대여 접수','intake','','primary'),date(S.data.today)+' · 매장 운영')+
      '<div class="so-metrics so-home-metrics">'+stats.map(([label,n,unit,hint,glyph,color,page])=>'<button class="so-metric" type="button" data-go="'+page+'"><span class="so-metric-glyph '+color+'">'+icon(glyph)+'</span>'+icon('arrow-up-right')+'<span class="so-metric-label">'+label+'</span><strong>'+n+'<em>'+unit+'</em></strong><small>'+hint+'</small></button>').join('')+'</div>'+
      '<div class="so-home-grid"><section class="so-panel so-today-work"><div class="so-panel-head"><div><h2>오늘 준비할 일 <span class="so-count-bubble">4</span></h2><p class="so-muted">예정 시간과 진행 상태를 함께 확인하세요.</p></div>'+link('전체 보기 '+icon('arrow-right'),'rentals','','quiet small')+'</div><div class="so-work-list"><div class="so-work-columns"><span>예정 시간</span><span>고객</span><span>업무 내용</span><span>상태</span><span></span></div>'+tasks.map(([n,desc,time,id,label,color])=>'<button class="so-work-item" type="button" data-go="rental" data-id="'+id+'"><span class="so-work-time '+(time.includes(':')?'':'is-label')+'">'+time+'</span><span class="so-work-name"><span class="so-avatar '+color+'">'+n[0]+'</span><strong>'+n+'</strong></span><span class="so-work-description">'+desc+'</span>'+status(label,color)+icon('chevron-right')+'</button>').join('')+'</div><div class="so-section-footer"><span>'+icon('info')+'수거한 장비는 매장에서 마지막으로 확인해 주세요.</span></div></section>'+
      '<section class="so-driver-preview"><div class="so-driver-label">'+icon('truck')+'1호 차량 · 다음 일정'+status('수거','purple')+'</div><div class="so-driver-slot"><strong>오후타임 후</strong><small>기준 16:30</small></div><div class="so-driver-place"><span>수거 장소</span><h2>만선 티롤 앞</h2><p>김영희 고객님 · 장비 5개</p></div><div class="so-driver-gear"><span>스키 <b>2</b></span><span>의류 <b>2</b></span><span>헬멧 <b>1</b></span></div>'+link('배달·수거 보드 열기 '+icon('arrow-right'),'dispatch','','driver-link')+'</section></div>'+
      '<div class="so-home-shortcuts">'+[['preparation','list-checks','방문 전 장비 준비','입력 응답과 날짜별 준비표'],['partners','handshake','거래처 장부','리프트권·장비 거래와 정산'],['closing','calculator','하루 마감','수납·미수와 현금 확인']].map(([route,glyph,title,desc])=>'<button type="button" class="so-shortcut" data-go="'+route+'"><span>'+icon(glyph)+'</span><div><strong>'+title+'</strong><small>'+desc+'</small></div>'+icon('chevron-right')+'</button>').join('')+'</div>';
  }
  function detail(){const o=selected(),current=S.state.tabs.rental||'items';const parts=[['items','장비·리프트권'],['return','수령·반납'],['payment','결제·환불'],['history','연락·변경 이력']];let body='';
    if(current==='items')body=panel('대여 품목','<div class="so-panel-pad so-stack"><div><h3>'+o.gear+'</h3><p class="so-muted">'+o.detail+'</p></div>'+(o.daily?'<table><thead><tr><th>이용일</th><th>스키 수량</th><th>할인 전</th></tr></thead><tbody>'+o.daily.map((q,i)=>'<tr><td>'+date(S.data.day(i))+'</td><td>'+q+'대</td><td>'+money(q*20000)+'</td></tr>').join('')+'</tbody></table>':'')+'<div class="so-counts"><span class="so-count">실제 지급<strong>'+o.issued+'</strong></span><span class="so-count">매장 확인<strong>'+o.returned+'</strong></span><span class="so-count">차량 수거<strong>'+o.collected+'</strong></span></div><div><h3>리프트권</h3><p>'+o.tickets+'</p></div><p class="so-note">'+o.note+'</p></div>');
    if(current==='return')body=panel('실제 수령·반납 내역','<div class="so-panel-pad so-stack"><div class="so-summary-line"><span>수령 예정</span><strong>'+date(o.pickup)+' '+o.pickupTime+'</strong></div><div class="so-summary-line"><span>반납 예정</span><strong>'+date(o.due)+' · '+o.slot+'</strong></div><div class="so-summary-line"><span>방법·장소</span><strong>'+o.method+' · '+o.place+'</strong></div><div class="so-counts"><span class="so-count">고객에게 남음<strong>'+Math.max(0,o.issued-o.returned-o.collected)+'</strong></span><span class="so-count">매장 확인 대기<strong>'+o.collected+'</strong></span></div><div class="so-actions">'+button('일부 반납 확인','rental-return',o.id,'soft')+button('반납 일정 변경','rental-schedule',o.id)+'</div><p class="so-muted">차량 인수와 매장 최종 확인은 별도로 표시합니다.</p></div>');
    if(current==='payment')body=panel('결제 내역','<div class="so-panel-pad so-stack"><div class="so-summary-line"><span>최종 대여금액</span><strong>'+money(o.amount)+'</strong></div><div class="so-summary-line"><span>받은 금액</span><strong>'+money(o.paid)+'</strong></div><div class="so-summary-line total"><span>받을 잔액</span><strong>'+money(o.amount-o.paid)+'</strong></div><div class="so-actions">'+button('수납 화면','rental-payment',o.id,'primary')+button('환불 화면','rental-refund',o.id)+'</div></div>');
    if(current==='history')body=panel('연락·변경 이력','<div class="so-panel-pad"><ul class="so-timeline"><li><time>14:40</time><div><strong>수량 확인 메모</strong><p>'+o.note+'</p></div></li><li><time>09:20</time><div><strong>대여 내용 확인</strong><p>'+o.gear+' · '+o.detail+'</p></div></li></ul><p class="so-preview-note">샘플 변경 이력입니다.</p></div>');
    return head(o.name+' 고객님',o.id+' · '+o.phone,button(icon('arrow-left')+'목록으로','back'),'대여 상세')+'<div class="so-main-detail"><div class="so-stack">'+S.tabs(parts,'items')+body+'</div>'+panel('대여 요약','<div class="so-panel-pad so-stack"><div>'+status(o.status,o.color)+'</div><div><p class="so-muted">이용 기간</p><h2>'+date(o.start)+' ~ '+date(o.end)+'</h2></div><div><p class="so-muted">반납 예정</p><h3>'+date(o.due)+' · '+o.slot+'</h3><p>'+o.method+'</p></div><div class="so-summary-line total"><span>미수금</span><strong>'+money(o.amount-o.paid)+'</strong></div><div class="so-actions">'+button('기간 연장','rental-extend',o.id)+button('장비 교환','rental-exchange',o.id)+button(icon('phone')+'연락','rental-contact',o.id)+'</div></div>')+'</div>';}
  for(const [action,title] of [['rental-return','일부 반납 · 매장 확인'],['rental-extend','이용 기간 연장'],['rental-exchange','장비 교환'],['rental-schedule','반납 일정 변경'],['rental-payment','수납 내역 입력'],['rental-refund','환불 내역 입력'],['rental-contact','고객 연락']])S.action(action,id=>{const o=orders.find(x=>x.id===id)||selected();let body='<p><strong>'+o.name+'</strong> · '+o.id+'</p>';
    if(action==='rental-return')body+='<div class="so-form-grid">'+o.items.map(([name,q,r])=>field(name+' 확인 수량',Math.max(0,q-r),'number','min="0" max="'+Math.max(0,q-r)+'"')).join('')+'</div>'+select('장비 상태',['수량 확인 · 세척 대기','이상 없음','점검 필요'])+'<p class="so-note">이미 확인한 수량과 고객에게 남은 수량을 대조하는 화면입니다.</p>';
    if(action==='rental-extend')body+='<div class="so-form-grid">'+field('현재 이용 종료일',o.end,'date','readonly')+field('변경할 종료일',S.data.day(2),'date')+'</div><p class="so-note">날짜별 장비 수량과 추가 요금을 확인한 뒤 변경하는 화면입니다.</p>';
    if(action==='rental-exchange')body+='<div class="so-form-grid">'+select('돌려받는 장비',o.items.map(i=>i[0]).concat(['없음']))+select('교환할 장비',['스키 · 일반','스키 · 고급','보드 · 일반'])+field('교환 수량',1,'number','min="1"')+field('사이즈·메모','부츠 260 → 265mm')+'</div>';
    if(action==='rental-schedule')body+='<div class="so-form-grid">'+field('반납일',o.due,'date')+select('반납 타임',['오후타임 후','야간타임 후','익일 오전','직접 시간'],o.slot)+select('반납 방법',['차량 수거','매장 직접'],o.method)+select('장소',['만선 티롤 앞','설천 주차장','만선 광장','스키샵'],o.place)+'</div>';
    if(action==='rental-payment'||action==='rental-refund')body+='<div class="so-summary-line"><span>받은 금액 / 받을 잔액</span><strong>'+money(o.paid)+' / '+money(o.amount-o.paid)+'</strong></div><div class="so-form-grid">'+select('결제 수단',['카드','현금','계좌이체'])+field(action==='rental-payment'?'받을 금액':'환불할 금액',action==='rental-payment'?o.amount-o.paid:0,'number','min="0"')+'</div>'+field('메모','','text','placeholder="정산·환불 사유"');
    if(action==='rental-contact')body+='<h2>'+o.phone+'</h2><div class="so-note">[우리 스키샵] 차량이 출발하였습니다. 5분 내로 도착하니 약속한 장소에서 대기해 주세요.</div><p class="so-muted">전화·문자 내용을 확인하는 화면입니다.</p>';
    S.preview(title,body);
  });
  function dispatch(){
    const base=orders.filter(o=>o.due===S.data.today&&o.items.length);
    const accepts=(o,t)=>t==='all'||t==='return'&&o.method==='차량 수거'||t==='delivery'&&o.id==='R-022'||t==='direct'&&o.method==='매장 직접';
    const list=base.filter(o=>accepts(o,tab()));
    const filters=[['all','전체'],['return','차량 수거'],['delivery','배달'],['direct','매장 직접']].map(([id,label])=>[id,label+'<span class="so-tab-count">'+base.filter(o=>accepts(o,id)).length+'</span>']);
    return head('배달·수거','시간과 장소를 확인하고 차량 업무를 살펴보세요.',link(icon('tablet')+'차량 화면','vehicle','','primary'))+'<div class="so-filter-panel">'+S.tabs(filters,'all')+'</div>'+panel('오늘의 일정','<div class="so-row-list so-dispatch-list"><div class="so-dispatch-columns"><span>예정 시간 · 타임</span><span>장소 · 방법</span><span>고객</span><span>실제 물품</span><span>상태</span><span>업무 처리</span></div>'+list.map(o=>{
      const delivery=o.id==='R-022';
      return '<div class="so-dispatch-row '+(delivery?'delivery':o.method==='매장 직접'?'direct':'')+'"><div><strong>'+(delivery?'16:40':o.time)+'</strong><small>'+(delivery?'배달 예정':o.slot)+'</small></div><div><strong>'+(delivery?'설천 주차장':o.place)+'</strong><small>'+(delivery?'차량 배달':o.method)+'</small></div><div><strong>'+o.name+'</strong><small>'+o.id+'</small></div><div>'+o.gear+'</div>'+status(delivery?'배달 대기':o.status==='매장 확인 대기'?'매장 확인 대기':o.method,delivery?'blue':o.status==='매장 확인 대기'?'purple':'orange')+'<div class="so-actions">'+link('업무 상세','rental',o.id,'small')+button(icon('bell')+'확인 요청','driver-alert',o.id,'small soft')+'</div></div>';
    }).join('')+'</div>');
  }
  S.action('driver-alert',id=>S.preview('기사님 확인 요청','<p>'+esc(id)+' 업무의 차량 알림 화면입니다.</p><div class="so-note">차량 화면에서 해당 업무 강조와 소리 알림으로 확인을 요청합니다.</div><p>이 시안에서는 실제 차량에 알림을 전송하지 않습니다.</p>'));
  function customers(){return head('고객관리','대표자 이름·연락처로 찾고 이용 내역을 확인하세요.')+'<div class="so-toolbar"><label class="so-field so-search">고객 찾기<input type="search" data-search="customers" placeholder="이름 또는 연락처"></label></div>'+panel('대표자 목록','<div id="so-customer-list" class="so-row-list">'+customerRows('')+'</div>');}
  function customerRows(q){const needle=q.replace(/[\s-]/g,'');const found=orders.filter(o=>o.name.includes(needle)||o.phone.replace(/-/g,'').includes(needle));return found.length?found.map(o=>'<div class="so-row so-customer-row"><div class="so-row-title"><span class="so-avatar">'+o.name[0]+'</span><strong>'+o.name+'</strong></div><span class="so-phone">'+o.phone.slice(0,-4)+'<b>'+o.phone.slice(-4)+'</b></span><span>'+o.gear+'</span><small class="so-customer-id">'+o.id+'</small>'+link('이용 내역 '+icon('chevron-right'),'rental',o.id,'small')+'</div>').join(''):'<p class="so-empty">검색한 고객이 없습니다.</p>';}
  S.search('customers',q=>{S.$('#so-customer-list').innerHTML=customerRows(q);});
  S.register('home',{title:'오늘 현황',render:home});S.register('intake',{title:'새 대여 접수'});S.register('rentals',{title:'렌탈현황',render:rentalList});S.register('rental',{title:'대여 상세',parent:'rentals',render:detail});S.register('dispatch',{title:'배달·수거',render:dispatch});S.register('vehicle',{title:'차량 태블릿'});S.register('customers',{title:'고객관리',render:customers});
})();
