(() => {
  const S=window.SkiOps,{head,panel,button,link,status,money,date,field,select,esc}=S;
  const products=[['ski','스키',20000,'일반 · 고급','대','스키 + 부츠 + 폴'],['board','보드',20000,'일반 · 고급','대','보드 + 부츠'],['clothes','의류',10000,'XS ~ 3XL','세트','상의 + 하의'],['visor','바이저 헬멧',10000,'S · M · L','개','바이저 일체형'],['helmet','헬멧',5000,'S · M · L','개','일반 헬멧'],['goggles','고글',5000,'성인 · 주니어','개','고글'],['pads','보호대',5000,'S · M · L','세트','무릎 + 엉덩이']];
  const ticketNames=[['오전권',40000,30000,'09:00 ~ 12:30'],['오후권',45000,35000,'12:30 ~ 16:30'],['야간권',40000,30000,'18:30 ~ 22:00'],['후야권',65000,50000,'12:30 ~ 22:00'],['3시간권',35000,25000,'시작 후 3시간'],['4시간권',45000,35000,'시작 후 4시간'],['6시간권',55000,45000,'시작 후 6시간'],['종일권',70000,55000,'09:00 ~ 16:30']];
  const tickets=ticketNames.flatMap(([name,adult,child,time],i)=>['성인','소인'].map((audience,j)=>({id:'L-'+i+'-'+j,name,audience,price:j?child:adult,time,purchase:Math.round((j?child:adult)*.8)})));
  const stock=[['스키 · 일반','150~160cm',24,7,2,3],['스키 · 고급','160~170cm',12,5,1,1],['보드 · 일반','145~155cm',18,8,2,2],['부츠 · 스키','260mm',12,6,2,2],['부츠 · 보드','240mm',8,3,1,1],['의류','L',20,7,3,4],['헬멧','M',15,4,2,1]];
  S.data.products=products;S.data.tickets=tickets;S.data.stock=stock;
  const current=()=>S.state.tabs.settings||'equipment';
  function productTable(){return '<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>장비 종류</th><th>등급·사이즈</th><th>기본 구성</th><th>1일 요금</th><th>상태</th><th></th></tr></thead><tbody>'+products.map(([id,name,price,size,unit,components])=>'<tr><td><strong>'+name+'</strong><small>수량 단위 · '+unit+'</small></td><td>'+size+'</td><td>'+components+'</td><td class="so-money"><strong>'+money(price)+'</strong></td><td>'+status('사용 중','green')+'</td><td>'+button('설정','product-edit',id,'small')+'</td></tr>').join('')+'</tbody></table></div>';}
  function ticketRows(query=''){const audience=S.state.filters.settingAudience||'all';const list=tickets.filter(t=>(audience==='all'||t.audience===audience)&&(t.name+' '+t.audience).includes(query.trim()));return list.length?list.map(t=>'<tr><td><strong>'+t.name+' · '+t.audience+'</strong><small>무주 · 샘플 권종</small></td><td>'+t.time+'<small>예시 이용시간</small></td><td class="so-money">'+money(t.price)+'</td><td class="so-money">'+money(t.purchase)+'</td><td>'+status('판매 중','green')+'</td><td><div class="so-actions">'+button('설정','ticket-edit',t.id,'small')+button('복사','ticket-copy',t.id,'small quiet')+'</div></td></tr>').join(''):'<tr><td colspan="6"><p class="so-empty">찾는 권종이 없습니다.</p></td></tr>';}
  function settingPage(){let content='';
    if(current()==='equipment')content=panel('장비 종류 · 요금',productTable(),button('장비 추가','product-edit','new','soft small'));
    if(current()==='tickets')content='<div class="so-toolbar"><label class="so-field so-search">권종 찾기<input type="search" data-search="setting-tickets" placeholder="오후, 후야, 4시간 등" value="'+esc(S.state.filters.settingQuery||'')+'"></label>'+select('대상',[['all','전체'],['성인','성인'],['소인','소인']],S.state.filters.settingAudience||'all','data-change="setting-audience"')+'</div>'+panel('리프트권 '+tickets.length+'종','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>권종·대상</th><th>이용시간</th><th>판매가</th><th>기준 매입가</th><th>상태</th><th></th></tr></thead><tbody id="so-setting-tickets">'+ticketRows(S.state.filters.settingQuery||'')+'</tbody></table></div>',button('권종 추가','ticket-edit','new','soft small'));
    if(current()==='discounts')content='<div class="so-grid2">'+[5000,10000].map((v,i)=>panel('간편 할인 '+(i+1),'<div class="so-panel-pad so-stack"><div class="so-form-grid">'+field('버튼 이름','단골 '+v.toLocaleString()+'원')+field('할인 금액',v,'number','min="0" step="1000"')+'</div><label class="so-check"><input type="checkbox" checked>장비당 할인에 표시</label><label class="so-check"><input type="checkbox" checked>총 금액 할인에 표시</label><div class="so-note">장비당은 실제 지급 수량 기준<br>총 할인은 누를 때마다 누적 · 리프트권 제외</div>'+button('버튼 모양 보기','discount-preview',String(v),'soft')+'</div>')).join('')+'</div>';
    if(current()==='operations')content='<div class="so-grid2">'+panel('반납 타임 기준','<div class="so-panel-pad so-stack">'+field('오후타임 후','16:30','time')+field('야간타임 후','22:00','time')+field('익일 오전','09:00','time')+'<p class="so-muted">익일 오전은 마지막 이용일의 다음 날입니다. 예시 기준이며 기존 거래에는 소급 적용하지 않습니다.</p></div>')+panel('매장·직원·차량','<div class="so-panel-pad so-stack">'+field('상호','우리 스키샵')+field('매장 연락처','010-0000-0000')+select('기본 수거 장소',['만선 티롤 앞','설천 주차장','만선 광장'])+select('차량',['1호 차량','2호 차량'])+button('직원 권한 보기','staff-preview','','soft')+'</div>')+'</div>';
    return head('매장 설정','대여 접수에서 사용할 장비·가격·권종을 관리합니다.',link('접수 화면 보기','intake','','primary'))+S.tabs([['equipment','장비·요금'],['tickets','리프트권'],['discounts','간편 할인'],['operations','운영·직원']],'equipment')+content+'<p class="so-preview-note">설정 화면 시안입니다. 입력값은 저장하거나 실제 가격표에 반영하지 않습니다.</p>';
  }
  S.search('setting-tickets',q=>{S.state.filters.settingQuery=q;S.$('#so-setting-tickets').innerHTML=ticketRows(q);});
  S.change('setting-audience',v=>{S.state.filters.settingAudience=v;S.render();});
  S.action('product-edit',id=>{const p=products.find(p=>p[0]===id)||['new','',0,'','개',''];S.modal(id==='new'?'장비 종류 추가':p[1]+' 설정','<div class="so-form-grid">'+field('장비 이름',p[1])+field('1일 요금',p[2],'number','data-preview-price min="0" step="1000"')+field('수량 단위',p[4])+field('등급·사이즈',p[3])+field('기본 구성',p[5])+select('상태',['사용 중','사용 중지'])+'</div><label class="so-check"><input type="checkbox" checked>반납 확인이 필요한 장비</label>'+S.previewNote+'<div class="so-dialog-actions">'+button('닫기','close')+button('1·2·3일 요금 보기','price-preview','','primary')+'</div>');});
  S.action('price-preview',()=>{const input=S.$('[data-preview-price]'),value=Number(input?.value);if(!Number.isFinite(value)||value<0||!input?.value.trim()){S.toast('0원 이상의 요금을 입력해 주세요.');return;}S.preview('이용일별 요금 미리보기','<p>장비 1개를 같은 수량으로 이용하는 예시</p><div>'+[1,2,3].map(n=>'<div class="so-summary-line"><span>'+n+'일 · 1개</span><strong>'+money(value*n)+'</strong></div>').join('')+'</div>');});
  for(const action of ['ticket-edit','ticket-copy'])S.action(action,id=>{const t=tickets.find(t=>t.id===id)||{name:'',audience:'성인',price:0,purchase:0,time:''};S.preview(action==='ticket-copy'?'리프트권 복사':id==='new'?'리프트권 추가':t.name+' 설정','<div class="so-form-grid">'+field('권종 이름',t.name+(action==='ticket-copy'?' 복사':''))+select('대상',['성인','소인'],t.audience)+field('판매가',t.price,'number','min="0"')+field('기준 매입가',t.purchase,'number','min="0"')+field('이용시간 안내',t.time)+select('사용일 조건',['전체 이용일','주중','주말·공휴일','지정일'])+select('판매 상태',['판매 중','판매 중지'])+field('표시 순서',1,'number','min="1"')+'</div><label class="so-check"><input type="checkbox" checked>자주 쓰는 권종에 표시</label><p class="so-muted">기준 매입가는 신규 거래의 제안값입니다. 실제 매입 단가는 거래처 장부에 따로 기록합니다.</p>');});
  S.action('discount-preview',id=>S.preview('간편 할인 버튼','<div class="so-actions">'+button('단골 '+money(Number(id)),'close','','soft')+'</div><p>장비당 할인과 총 금액 할인에 표시할 버튼 예시입니다.</p>'));
  S.action('staff-preview',()=>S.preview('직원 권한','<div class="so-row-list">'+[['관리자','가격·정산·직원 설정'],['카운터','접수·준비·반납 확인'],['기사님','담당 배달·수거·연락']].map(([a,b])=>'<div class="so-row"><strong>'+a+'</strong><span>'+b+'</span></div>').join('')+'</div><p class="so-muted">권한 구성 예시입니다. 현재 체험 화면에 실제 인증은 없습니다.</p>'));
  function inventory(){const t=S.state.tabs.inventory||'equipment';let body='';
    if(t==='equipment')body=panel('장비 · 사이즈별 재고','<div class="so-table-wrap"><table class="so-responsive-table"><thead><tr><th>품목·사이즈</th><th>보유</th><th>대여 중</th><th>예약 배정</th><th>세척·정비</th><th>대여 가능</th><th></th></tr></thead><tbody>'+stock.map(([name,size,total,out,reserved,service],i)=>'<tr><td><strong>'+name+'</strong><small>'+size+'</small></td><td data-label="보유">'+total+'</td><td data-label="대여 중">'+out+'</td><td data-label="배정">'+reserved+'</td><td data-label="세척·정비">'+service+'</td><td data-label="대여 가능">'+status((total-out-reserved-service)+'개',total-out-reserved-service<=2?'orange':'green')+'</td><td>'+button('상세','stock-detail',String(i),'small')+'</td></tr>').join('')+'</tbody></table></div>');
    if(t==='tickets')body=panel('리프트권 보유·전달','<div class="so-row-list">'+[['오후권 · 성인','입고 20 · 판매 11 · 보유 9','고객 전달 대기 4'],['후야권 · 성인','입고 10 · 판매 0 · 보유 10','고객 전달 대기 0'],['야간권 · 성인','입고 15 · 고객 1 / 업체 6 · 보유 8','고객 전달 대기 1']].map(([n,q,state])=>'<div class="so-row"><div><strong>'+n+'</strong><p class="so-muted">'+q+'</p></div>'+status(state,'orange')+button('입출고 내역','ticket-stock',n,'small')+'</div>').join('')+'</div>')+'<p class="so-preview-note">실물 보유형의 샘플 수량입니다. 실제 리조트 발권·코드 조회와 연결되어 있지 않습니다.</p>';
    if(t==='external')body=panel('다른 매장과 주고받은 장비','<div class="so-row-list"><div class="so-row"><div><strong>A스키샵 · 우리 스키 5대</strong><p class="so-muted">빌려줌 · '+date(S.data.day(1))+' 오후타임 후 돌려받기</p></div>'+status('돌려받을 장비 5대','orange')+link('거래처 내역','partner','P-001','small')+'</div><div class="so-row"><div><strong>B스키샵 · 타 매장 스키 5대</strong><p class="so-muted">빌려옴 · 3대 반환, 2대 남음</p></div>'+status('돌려줄 장비 2대','purple')+link('거래처 내역','partner','P-002','small')+'</div></div>');
    if(t==='service')body=panel('세척·건조·정비 대기','<div class="so-row-list">'+[['의류 L · 4세트','건조 대기','green'],['스키 일반 · 3대','정비 중','orange'],['부츠 260mm · 2켤레','세척 대기','purple']].map(([n,state,c])=>'<div class="so-row"><div><strong>'+n+'</strong><p class="so-muted">현재 대여 가능 수량에서 제외</p></div>'+status(state,c)+button('점검 화면','service-detail',n,'small')+'</div>').join('')+'</div>');
    return head('재고·정비','현재 빌려줄 수 있는 수량과 준비가 필요한 장비를 확인합니다.',link('상품 설정','settings','','soft'))+S.tabs([['equipment','장비·사이즈'],['tickets','리프트권'],['external','타 매장 장비'],['service','세척·정비']],'equipment')+body;
  }
  S.action('stock-detail',id=>{const [name,size,total,out,reserved,service]=stock[Number(id)];S.preview(name+' · '+size,'<div>'+[['보유 수량',total],['대여 중',out],['예약 배정',reserved],['세척·정비',service],['대여 가능',total-out-reserved-service]].map(([l,n])=>'<div class="so-summary-line"><span>'+l+'</span><strong>'+n+'개</strong></div>').join('')+'</div>');});
  S.action('ticket-stock',name=>S.preview(name+' 입출고','<ul class="so-timeline"><li><time>08:00</time><div>거래처 매입 입고 · 샘플 거래</div></li><li><time>09:20</time><div>고객 판매 · 전달 상태 별도 확인</div></li></ul>'));
  S.action('service-detail',name=>S.preview('장비 점검','<p><strong>'+name+'</strong></p>'+select('점검 상태',['세척 대기','건조 대기','정비 중','대여 가능'])+field('점검 메모','')+'<p class="so-muted">매장 반납 확인 후에도 준비가 끝나야 재대여할 수 있습니다.</p>'));
  S.register('settings',{title:'매장 설정',render:settingPage});S.register('inventory',{title:'재고·정비',render:inventory});
})();
