(() => {
  'use strict';
  const S = window.SkiOps, F = S.workflow, C = window.SkiWorkflowClient;
  const { esc: e, button: b, link: go, field, select, status } = S;
  const ui = { date: S.data.today, basis: 'use', vehicleTab: 'jobs', selected: null, completed: false, returnFilter: 'all', returnQuery: '', reservationDays: [] };
  const label = kind => ({ collection: '수거', delivery: '전달', refund: '환불', load: '차량 적재', collect: '차량 수거', deliver: '고객 전달', receive: '매장 인계', directReturn: '직접 반납', 'stock.opening': '보유 수량 등록', 'ticket.issue': '신규 발권' }[kind] || kind);
  const name = id => S.workflowCustomer(id).name;
  const stamp = at => new Intl.DateTimeFormat('ko-KR', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'Asia/Seoul' }).format(new Date(at));
  const locationName = a => a.kind === 'shop' ? '매장' : a.kind === 'vehicle' ? a.id === F.vehicleId ? '1호 차량' : '2호 차량' : a.kind === 'vendor' ? '환불 완료' : name(a.id);
  const tag = (text, color = 'grey') => status(text, color);
  const row = (title, sub, actions = '') => '<div class="wf-row"><div class="wf-copy"><strong>' + title + '</strong>' + (sub ? '<p>' + sub + '</p>' : '') + '</div><div class="wf-actions">' + actions + '</div></div>';
  const head = (title, sub, actions = '') => '<header class="wf-head"><div><h1>' + title + '</h1><p>' + sub + '</p></div><div class="wf-actions">' + actions + '</div></header>';
  const panel = (title, body, actions = '') => '<section class="wf-panel"><header><h2>' + title + '</h2><div class="wf-actions">' + actions + '</div></header>' + body + '</section>';
  const empty = text => '<p class="wf-empty">' + text + '</p>';
  const totals = ids => F.snap().catalog.map(s => ({ ...s, quantity: F.assets(ids).filter(a => a.sku === s.id).length })).filter(s => s.quantity);
  const textItems = ids => totals(ids).map(s => e(s.label) + ' <b>' + s.quantity + s.unit + '</b>').join(' · ') || '없음';
  const unitCards = ids => '<div class="wf-quantities">' + totals(ids).map(s => '<div><span>' + e(s.label) + '</span><strong>' + s.quantity + '<small>' + s.unit + '</small></strong></div>').join('') + '</div>';
  const countInput = (labelText, key, value, max = 500) => '<div class="wf-count"><button type="button" data-action="wf-step" data-id="' + key + ':-1" aria-label="' + e(labelText) + ' 줄이기">−</button><input id="' + key + '" aria-label="' + e(labelText) + ' 수량" type="number" min="0" max="' + max + '" value="' + value + '"><button type="button" data-action="wf-step" data-id="' + key + ':1" aria-label="' + e(labelText) + ' 늘리기">+</button></div>';
  const read = id => S.$('#' + id)?.value || '';
  const number = id => { const n = Number(read(id)), input = S.$('#' + id); if (!Number.isSafeInteger(n) || n < +(input?.min || 0) || n > +(input?.max || 500)) throw new Error('수량을 확인해 주세요.'); return n; };
  const changed = message => { syncBase(); S.close(); S.render(); S.toast(message || '반영했습니다.'); };
  function syncBase() {
    for (const base of S.data.orders) { const o = F.projectOrder(base.id); if (!o) continue; const eq = o.items.filter(i => i.category !== 'liftTicket'); base.issued = eq.reduce((n, i) => n + i.issuedQuantity, 0); base.returned = eq.reduce((n, i) => n + i.shopQuantity, 0); base.collected = eq.reduce((n, i) => n + i.vehicleQuantity, 0); base.status = ({ in_use: '대여 중', partial_return: '일부 반납', awaiting_shop: '매장 확인 대기', awaiting_issue: '수령 예정', returned: '반납 완료' })[o.status]; }
  }
  let actionBusy = false;
  function safe(fn) { return async (...args) => { if (actionBusy) return; actionBusy = true; try { await fn(...args); } catch (error) { const el = S.$('#wf-error'); if (el) { el.textContent = error.message; el.hidden = false; } else S.toast(error.message); } finally { actionBusy = false; } }; }
  function modal(title, body, footer) { S.modal(title, '<div class="wf-modal-content">' + body + '<p id="wf-error" class="wf-error" role="alert" hidden></p></div><footer class="wf-modal-footer">' + footer + '</footer>'); }
  const dayPicker = key => '<div class="wf-actions">' + b('오늘', 'wf-date', key + ':today', ui.date === S.data.today ? 'soft' : '') + b('내일', 'wf-date', key + ':tomorrow', ui.date === S.data.day(1) ? 'soft' : '') + '<input type="date" aria-label="조회 날짜" value="' + ui.date + '" data-change="wf-date"></div>';
  const vehicleDayPicker = () => '<div class="wf-day-picker" role="group" aria-label="방문 날짜">' + b('오늘', 'wf-date', 'vehicle:today', ui.date === S.data.today ? 'soft' : '') + b('내일', 'wf-date', 'vehicle:tomorrow', ui.date === S.data.day(1) ? 'soft' : '') + '<input class="wf-date-control" type="date" aria-label="조회 날짜" value="' + ui.date + '" data-change="wf-date"></div>';
  const stock = () => { const v = F.store.vehicle({ vehicleId: F.vehicleId }); return '<section class="wf-stock" aria-label="현재 차량 보관 수량"><div class="wf-stock-label"><strong>1호 차량</strong><span>현재 보관</span></div>' + v.totals.filter(s => ['ski', 'board', 'clothing', 'helmet', 'ticket-3h', 'ticket-4h', 'ticket-6h'].includes(s.sku) || s.current).map(s => '<div class="wf-stock-item"><span>' + e(s.label) + '</span><strong>' + s.current + '<small>' + s.unit + '</small></strong></div>').join('') + '</section>'; };
  const vehicleStockRows = kind => F.store.vehicle({ vehicleId: F.vehicleId }).totals.filter(s => (s.kind === 'liftTicket') === (kind === 'tickets') && (['ski', 'board', 'clothing', 'helmet', 'ticket-3h', 'ticket-4h', 'ticket-6h'].includes(s.sku) || s.current));
  const vehicleStockButtons = (selected = '') => '<div class="wf-stock-triggers" role="group" aria-label="현재 차량 보관">' + [['equipment', '장비', '개'], ['tickets', '리프트권', '매']].map(([id, title, unit]) => '<button type="button" class="so-button wf-stock-trigger ' + (id === selected ? 'soft' : '') + '" data-action="wf-stock-popup" data-id="' + id + '" aria-haspopup="dialog">' + title + '<strong>' + vehicleStockRows(id).reduce((n, s) => n + s.current, 0) + '<small>' + unit + '</small></strong></button>').join('') + '</div>';
  const vehicleHeaderTools = () => '<div class="wf-vehicle-header-tools">' + vehicleDayPicker() + vehicleStockButtons() + '</div>';
  function openVehicleStock(kind) {
    const rows = vehicleStockRows(kind);
    modal('1호 차량 · 현재 보관', '<div class="wf-stock-popup">' + vehicleStockButtons(kind) + '<div class="wf-stock-counts">' + rows.map(s => '<div><span>' + e(s.label) + '</span><strong>' + s.current + '<small>' + e(s.unit) + '</small></strong></div>').join('') + '</div></div>', b('닫기', 'close'));
  }
  const board = () => F.store.board({ vehicleId: F.vehicleId, date: ui.date, ...(ui.selected ? { selectedTaskId: ui.selected } : {}) });
  function notices() {
    const records = S.notificationRuntime.driver.sync(0).records.filter(n => n.lifecycle === 'active' && !n.acknowledgedAt && ['sequence', 'priority'].includes(n.type));
    if (!records.length) return '';
    const sequence = records.find(n => n.type === 'sequence'), priority = records.find(n => n.type === 'priority');
    const shown = priority && sequence ? [priority, sequence] : records.slice(0, 2);
    return '<div class="wf-alerts" aria-live="polite">' + shown.map(n => {
      const isSequence = n.type === 'sequence', task = F.snap().tasks.find(t => t.id === n.taskId);
      const customerName = task ? (task.customerId ? name(task.customerId) : task.title) : S.data.orders.find(o => o.id === n.orderId)?.name || n.title.split(' · ')[0];
      const change = n.changes?.find(c => c.taskId === n.taskId) || n.changes?.[0];
      const summary = isSequence ? (change && !n.summary.startsWith('시간순으로 복원') ? (task ? customerName : change.title.replace(/ 수거$| 전달$/, '')) + ' ' + change.fromRank + ' → ' + change.toRank + '번째' : '시간순으로 복원') : customerName;
      const sequenceName = task?.kind === 'refund' ? customerName.replace(/^리프트권 /, '') : task ? customerName : change?.title.replace(/ 수거$| 전달$/, '');
      const detail = isSequence && change && !n.summary.startsWith('시간순으로 복원') ? '<span class="wf-alert-name">' + e(sequenceName) + '</span><span class="wf-alert-rank">' + change.fromRank + '→' + change.toRank + '번째</span>' : '<span class="wf-alert-name">' + e(summary) + '</span>';
      return '<button type="button" class="wf-alert ' + n.type + '" data-action="wf-ack" data-id="' + e(n.id) + '" aria-label="' + (isSequence ? '순서 확인: ' : '요청 확인: ') + e(summary) + '" title="' + e(n.summary + ' · ' + stamp(n.createdAt)) + '"><span class="wf-alert-icon" aria-hidden="true">' + S.icon(isSequence ? 'arrow-up-down' : 'bell-ring') + '</span><span class="wf-alert-copy"><strong>' + (isSequence ? '매장 순서 변경' : '우선 확인 요청') + '</strong><span class="wf-alert-summary">' + detail + '</span></span><span class="wf-alert-check">확인</span></button>';
    }).join('') + (records.length > shown.length ? b('외 ' + (records.length - shown.length) + '건', 'wf-notices', '', 'wf-more-notices') : '') + '</div>';
  }
  function taskRow(t, counter = false) {
    const ids = F.remaining(t), customer = S.workflowCustomer(t.customerId);
    const content = '<span class="wf-rank">' + (t.rank || '·') + '</span><div class="wf-copy"><div class="wf-task-meta">' + tag(label(t.kind), t.kind === 'refund' ? 'purple' : t.kind === 'delivery' ? 'blue' : 'orange') + '<time>' + e(t.time) + '</time></div><strong>' + e(customer.name === t.customerId || !t.customerId ? t.title : customer.name) + '</strong><p>' + e(t.place) + '</p><small>' + textItems(ids) + '</small></div>';
    if (!counter) return '<button type="button" class="wf-task ' + (ui.selected === t.id ? 'selected' : '') + '" data-action="wf-select" data-id="' + t.id + '" aria-pressed="' + (ui.selected === t.id) + '">' + content + '</button>';
    return '<div class="wf-task counter">' + content + '<div class="wf-actions">' + b('맨 위', 'wf-order', t.id + ':top') + b('↑ 위로', 'wf-order', t.id + ':up') + b('↓ 아래로', 'wf-order', t.id + ':down') + b('우선 확인', 'wf-priority', t.id) + b('업무 보기', 'wf-open-task', t.id) + (t.kind !== 'refund' && !t.formId ? b('업무 취소', 'wf-task-cancel', t.id) : '') + '</div></div>';
  }
  function taskDetail(t) {
    if (!t) return panel('방문 업무', empty('남은 업무가 없습니다.'));
    const customer = S.workflowCustomer(t.customerId), ids = F.remaining(t), refund = F.snap().refunds.find(r => r.id === t.refundId);
    return '<article class="wf-detail"><header><div>' + tag(label(t.kind), 'purple') + '<strong>' + e(t.time) + '</strong></div><h2>' + e(t.place) + '</h2><p class="wf-customer">' + e(t.customerId ? customer.name : '리프트권 환불') + (customer.phone ? '<a href="tel:' + e(customer.phone) + '">' + e(customer.phone) + '</a>' : '') + '</p></header><div class="wf-detail-body"><p>' + (refund ? '환불 완료 ' + refund.completedQuantity + '매 · 남은 ' + refund.remainingQuantity + '매' : '이번에 ' + label(t.kind) + '할 물품') + '</p>' + unitCards(ids) + (t.kind === 'delivery' && F.assets(ids).some(a => a.location.kind !== 'vehicle') ? '<p class="wf-hint">매장 적재 또는 앞 고객 수거가 필요한 물품이 있습니다.</p>' : '') + (refund?.attempts.length ? '<p class="wf-hint">최근 기록: ' + e(refund.attempts.at(-1).note || '일부 환불') + '</p>' : '') + '</div><footer class="wf-detail-footer">' + b(refund ? '환불 결과 입력' : label(t.kind) + ' 수량 확인', 'wf-task-move', t.id, 'primary') + b('매장에 확인 요청', 'wf-help', t.id) + '</footer></article>';
  }
  function renderVehicle() {
    const list = board(); ui.selected = list.selectedTaskId;
    const tasks = [...list.inProgress, ...list.pending];
    return '<div class="wf wf-vehicle"><div class="wf-vehicle-toolbar"><div class="wf-actions wf-vehicle-tabs">' + [['jobs', '방문 업무'], ['stock', '적재 내역'], ['history', '처리 내역']].map(([id, text]) => b(text, 'wf-vehicle-tab', id, ui.vehicleTab === id ? 'soft' : '')).join('') + '</div><div class="wf-toolbar-notices">' + notices() + '</div></div>' + (ui.vehicleTab === 'jobs' ? '<div class="wf-vehicle-grid"><section class="wf-job-column"><h2>남은 방문 ' + tasks.length + '건 <small>' + (list.manualOrder ? '매장 지정 순서' : '시간순') + '</small></h2><div class="wf-job-scroll">' + (tasks.map(t => taskRow(t)).join('') || empty('오늘 업무를 모두 마쳤습니다.')) + '</div></section><div class="wf-work-column">' + taskDetail(tasks.find(t => t.id === ui.selected)) + '</div></div>' : '<div class="wf-scroll">' + (ui.vehicleTab === 'stock' ? inventoryRows(true) : historyRows(true)) + '</div>') + '</div>';
  }
  function groups(rows) { const map = new Map(); for (const a of rows) { const k = [a.lotId, a.location.kind, a.location.id, a.purpose, a.refundId || ''].join('|'); if (!map.has(k)) map.set(k, []); map.get(k).push(a); } return [...map.values()]; }
  function inventoryRows(driverOnly = false) {
    const state = F.snap(), records = groups(state.assets.filter(a => driverOnly ? a.location.kind === 'vehicle' && a.location.id === F.vehicleId : a.ticket && a.location.kind !== 'vendor'));
    return panel(driverOnly ? '실제로 차량에 있는 물품' : '리프트권 현재 보관', (records.map(items => {
      const a = items[0], sku = state.catalog.find(s => s.id === a.sku), allocations = state.allocations.filter(x => items.some(y => y.id === x.assetId) && x.status === 'active' && !x.fulfilledAt);
      const nextNames = [...new Set(allocations.map(x => name(x.reservationId)))];
      return row(e(sku.label) + ' <b>' + items.length + sku.unit + '</b> ' + tag(locationName(a.location), 'blue'), (a.ticket ? '유효 ' + stamp(a.ticket.validFrom) + ' ~ ' + stamp(a.ticket.validTo) + '<br>' : '') + (a.refundId ? '환불 예정 · ' : a.vehicleOrigin === 'customer' ? '고객에게 수거 · ' : a.vehicleOrigin === 'shop' ? '매장에서 적재 · ' + (a.purpose === 'delivery' ? '고객 전달용 · ' : '예비용 · ') : '') + (nextNames.length ? '전달 예정: ' + e(nextNames.join(', ')) : '다음 고객 미배정'), driverOnly ? '' : (a.location.kind === 'shop' ? b('차량에 적재', 'wf-bundle-load', a.id) : a.location.kind === 'vehicle' ? b('매장 인계', 'wf-bundle-receive', a.id) : '') + (['shop', 'vehicle'].includes(a.location.kind) && !a.refundId ? b('환불 배정', 'wf-bundle-refund', a.id) : '') + (a.ticket && !a.refundId ? b('다음 고객 배정', 'wf-next', a.id) : ''));
    }).join('') || empty('보관 중인 물품이 없습니다.')));
  }
  function historyRows(driverOnly = false) {
    const state = F.snap();
    const rows = F.store.history().movements.filter(m => !m.kind.startsWith('stock.') && (!driverOnly || m.from?.kind === 'vehicle' || m.to?.kind === 'vehicle')).slice().reverse();
    return panel('물품 이동 기록', rows.map(m => row(label(m.kind), stamp(m.at) + ' · ' + (m.from ? e(locationName(m.from)) + ' → ' : '') + e(locationName(m.to)) + '<br>' + textItems(m.assetIds.filter(id => !m.reversedAssetIds.includes(id))) + (m.reversedAssetIds.length ? ' · 정정 ' + m.reversedAssetIds.length + '개' : ''), !driverOnly && ['load', 'collect', 'deliver', 'receive', 'directReturn'].includes(m.kind) && !m.intakeId ? b('수량 정정', 'wf-correct', m.id) : '')).join('') || empty('처리 기록이 없습니다.'));
  }
  function vehicleStockPage() {
    return '<div class="wf">' + head('차량 적재·매장 인계', '카운터에서 실제 실은 수량과 내려놓은 수량을 확인합니다.', b('차량 적재', 'wf-load', '', 'primary') + b('매장 인계 확인', 'wf-receive')) + stock() + '<div class="wf-scroll">' + inventoryRows(true) + historyRows() + '</div></div>';
  }
  function reservations() {
    const result = F.store.reservations({ date: ui.date, basis: ui.basis });
    return '<div class="wf">' + head('리프트권 예약·발권', '예약 이용일과 발권일을 나눠 확인하세요.', b('예약 입력', 'wf-book-new', '', 'primary') + b('취소 예약', 'wf-cancelled-list') + go('보관·환불', 'lift-stock')) + '<div class="wf-toolbar">' + dayPicker('reservations') + '<div class="wf-actions">' + b('이용일 기준', 'wf-basis', 'use', ui.basis === 'use' ? 'soft' : '') + b('발권일 기준', 'wf-basis', 'issue', ui.basis === 'issue' ? 'soft' : '') + '</div></div><div class="wf-metrics">' + result.totals.filter(t => ['ticket-3h', 'ticket-4h', 'ticket-6h'].includes(t.ticketType) || t.reserved).map(t => '<div><h2>' + e(t.label) + '</h2><strong>' + t.needIssue + '<small>매 미확보</small></strong><p>예약 ' + t.reserved + ' · 확보 ' + t.secured + ' · 회수 대기 ' + t.waitingRecovery + '</p></div>').join('') + '</div><div class="wf-scroll">' + (result.overdue.length ? '<p class="wf-error">이전 발권일에 미확보 ' + result.overdue.reduce((n, r) => n + r.needIssue, 0) + '매가 있습니다.</p>' : '') + (result.rows.map(r => row(e(r.customer.name) + ' · ' + e(r.customer.phone), e(r.ticketType.replace('ticket-', '').replace('h', '시간권')) + ' <b>' + r.reserved + '매</b> · 확보 ' + r.secured + ' / 회수 대기 ' + r.waitingRecovery + '<br>이용 ' + e(r.useDate) + (r.startTime ? ' ' + r.startTime + '~' + r.endTime : '') + ' · 발권 ' + e(r.issueDate), b('발권·배정', 'wf-book-detail', r.reservationId + '|' + r.id) + b('예약 변경', 'wf-book-edit', r.reservationId + '|' + r.id))).join('') || empty('이 날짜의 예약이 없습니다.')) + '</div></div>';
  }
  function liftStock() { const refunds = F.snap().refunds; return '<div class="wf">' + head('리프트권 보관·환불', '현재 위치와 다음 고객, 환불 잔량을 함께 확인합니다.', b('보유권 등록', 'wf-ticket-new') + go('예약·발권', 'lift-reservations')) + '<div class="wf-scroll">' + panel('환불 업무', refunds.map(r => row('환불 ' + r.plannedQuantity + '매 · 완료 ' + r.completedQuantity + ' / 남음 ' + r.remainingQuantity, e(r.status === 'partial' ? '일부 환불 · 남은 수량 재처리 가능' : r.status === 'incomplete' ? '미처리 · 사유 확인 후 재시도' : r.remainingQuantity ? '환불 대기' : '종료') + ' · 차량 보관 ' + r.onboardQuantity + '매 · 실제 환불액 ' + S.money(r.amountWon), r.remainingQuantity ? b('환불 결과 입력', 'wf-refund-result', r.id) + b('남은 환불 취소', 'wf-refund-cancel', r.id) : tag('처리 완료', 'green'))).join('')) + inventoryRows() + '</div></div>'; }
  let picker = null;
  function openPicker(title, rows, apply, extra = '') {
    picker = { rows: groups(rows), apply };
    modal(title, extra + (picker.rows.length ? picker.rows.map((group, i) => { const a = group[0], sku = F.snap().catalog.find(s => s.id === a.sku); return row(e(sku.label) + ' · ' + group.length + sku.unit + ' 가능', a.ticket ? stamp(a.ticket.validTo) + '까지 · ' + (a.refundId ? '환불 예정' : e(locationName(a.location))) : e(locationName(a.location)), countInput(sku.label, 'wf-q-' + i, 0, group.length)); }).join('') : empty('처리할 수 있는 물품이 없습니다.')), b('모두 선택', 'wf-pick-all') + b('취소', 'close') + b('선택 수량 확인', 'wf-pick-apply', '', 'primary'));
  }
  S.action('wf-pick-all', () => picker.rows.forEach((group, i) => { S.$('#wf-q-' + i).value = group.length; }));
  function pickRows() { return picker.rows.flatMap((group, i) => group.slice(0, number('wf-q-' + i)).map(a => a.id)); }
  S.action('wf-pick-apply', safe(() => { const ids = pickRows(); if (!ids.length) throw new Error('처리할 수량을 선택해 주세요.'); picker.apply(ids); }));
  function movement(kind, rows, options = {}) {
    openPicker(label(kind) + ' 수량 확인', rows, ids => { F.run('stock.move', { kind, assetIds: ids, ...options, ...(kind === 'load' ? { purpose: S.$('[name="wf-load-purpose"]:checked')?.value || options.purpose || 'spare' } : {}) }, S.state.page === 'vehicle' ? 'driver' : 'store');
      if (options.taskId) { const task = F.snap().tasks.find(t => t.id === options.taskId); if (!F.remaining(task).length) F.run('task.status', { id: task.id, status: 'completed' }, S.state.page === 'vehicle' ? 'driver' : 'store'); }
      changed('실제 처리한 수량을 반영했습니다. 남은 수량은 계속 표시됩니다.');
    }, '<p class="wf-hint">실제로 ' + label(kind) + '한 수량만 선택하세요.</p>' + (kind === 'load' ? '<fieldset class="wf-checks"><legend>적재 용도</legend><label><input type="radio" name="wf-load-purpose" value="spare" checked>예비용</label><label><input type="radio" name="wf-load-purpose" value="delivery">고객 전달용</label></fieldset><p class="wf-hint">환불 배정된 권은 환불 용도를 유지합니다.</p>' : ''));
  }
  function taskMove(id) {
    const t = F.snap().tasks.find(t => t.id === id); if (!t) throw new Error('업무를 찾을 수 없습니다.');
    if (t.refundId) return refundResult(t.refundId);
    const kind = t.kind === 'collection' ? 'collect' : 'deliver', from = kind === 'collect' ? { kind: 'customer', id: t.customerId } : F.van, to = kind === 'collect' ? F.van : { kind: 'customer', id: t.customerId };
    movement(kind, F.assets(F.remaining(t)).filter(a => a.location.kind === from.kind && a.location.id === from.id), { from, to, taskId: t.id });
  }
  function refundResult(id) {
    const r = F.snap().refunds.find(x => x.id === id), qty = r.onboardQuantity;
    modal('환불 결과 · 남은 ' + r.remainingQuantity + '매', '<p>실제로 환불한 권만 차량 보관에서 빠집니다.</p>' + row('이번 환불 완료', '현재 차량에서 처리 가능 ' + qty + '매', countInput('환불 완료', 'wf-refund-qty', qty, qty)) + field('실제 환불액 (원)', '0', 'number', 'id="wf-refund-money" min="0" max="100000000"') + select('미처리 사유', [['', '모두 처리 / 별도 사유 없음'], ['발권처 확인 필요', '발권처 확인 필요'], ['환불 불가 안내', '환불 불가 안내'], ['매표소 업무 종료', '매표소 업무 종료']], '', 'id="wf-refund-note"'), b('닫기', 'close') + b('결과 저장', 'wf-refund-save', id, 'primary'));
  }
  function bundle(id) { const a = F.snap().assets.find(x => x.id === id); return groups(F.snap().assets).find(g => g.some(x => x.id === id)) || [a]; }
  S.action('wf-refund-save', safe(id => { const r = F.snap().refunds.find(x => x.id === id), quantity = number('wf-refund-qty'), amountWon = number('wf-refund-money'), note = read('wf-refund-note'); const ids = F.snap().assets.filter(a => a.refundId === id && a.location.kind === 'vehicle' && a.location.id === r.vehicleId).slice(0, quantity).map(a => a.id); F.run('refund.complete', { id, assetIds: ids, amountWon, note }, S.state.page === 'vehicle' ? 'driver' : 'store'); changed('환불 완료 ' + quantity + '매 · 남음 ' + (r.remainingQuantity - quantity) + '매'); }));
  S.action('wf-refund-result', safe(refundResult));
  S.action('wf-refund-cancel', safe(id => { const r = F.snap().refunds.find(x => x.id === id); openPicker('남은 환불 예정 취소', F.assets(r.assetIds).filter(a => a.refundId === id), ids => { F.run('refund.cancel', { id, assetIds: ids, reason: '카운터에서 환불 예정 취소' }); changed('환불 예정을 취소했습니다. 실물 보관 위치는 그대로입니다.'); }); }));
  S.action('wf-bundle-refund', safe(id => openPicker('리프트권 환불 배정', bundle(id), ids => { F.run('refund.plan', { id: C.randomId('refund-'), assetIds: ids, vehicleId: F.vehicleId, vendorId: F.assets(ids)[0].ticket.vendorId, date: read('wf-refund-date'), time: read('wf-refund-time'), place: read('wf-refund-place') }); changed('환불 업무를 배정했습니다. 매장에 있는 권은 차량에 적재해 주세요.'); }, '<div class="wf-form-grid">' + field('환불 날짜', S.data.today, 'date', 'id="wf-refund-date"') + field('방문 시간', '16:00', 'time', 'id="wf-refund-time"') + field('방문 장소', '리조트 매표소', 'text', 'id="wf-refund-place"') + '</div>')));
  S.action('wf-bundle-load', safe(id => movement('load', bundle(id), { from: F.shop, to: F.van, purpose: 'spare' })));
  S.action('wf-bundle-receive', safe(id => movement('receive', bundle(id), { from: F.van, to: F.shop })));
  S.action('wf-load', safe(() => movement('load', F.snap().assets.filter(a => a.location.kind === 'shop'), { from: F.shop, to: F.van, purpose: 'spare' })));
  S.action('wf-receive', safe(() => movement('receive', F.snap().assets.filter(a => a.location.kind === 'vehicle' && a.location.id === F.vehicleId), { from: F.van, to: F.shop })));
  S.action('wf-step', (value) => { const [id, delta] = value.split(':'), input = S.$('#' + id); input.value = Math.max(+(input.min || 0), Math.min(+(input.max || 500), +input.value + +delta)); input.dispatchEvent(new Event('input', { bubbles: true })); });
  S.action('wf-select', id => { ui.selected = id; S.render(); });
  S.action('wf-vehicle-tab', id => { ui.vehicleTab = id; S.render(); });
  S.action('wf-task-move', safe(taskMove));
  const openTask = id => { const task = F.snap().tasks.find(t => t.id === id); if (task) ui.date = task.date; ui.selected = id; S.go('vehicle'); };
  S.action('wf-open-task', openTask);
  S.action('wf-stock-page', () => S.go('vehicle-stock'));
  S.action('wf-stock-popup', openVehicleStock);
  S.$('#so-dialog').addEventListener('click', event => {
    const dialog = event.currentTarget;
    if (event.target !== dialog || !dialog.querySelector('.wf-stock-popup')) return;
    const bounds = dialog.getBoundingClientRect();
    if (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom) S.close();
  });
  S.action('wf-completed', () => { ui.completed = !ui.completed; S.render(); });
  S.action('wf-order', safe(value => { const i = value.lastIndexOf(':'), taskId = value.slice(0, i), action = value.slice(i + 1); F.run('dispatch.reorder', { vehicleId: F.vehicleId, date: ui.date, taskId, action }); changed('차량에 순서 변경 안내를 표시했습니다.'); }));
  S.action('wf-restore', safe(() => { F.run('dispatch.reorder', { vehicleId: F.vehicleId, date: ui.date, action: 'restore' }); changed('시간순으로 복원했습니다.'); }));
  S.action('wf-priority', safe(id => { F.run('task.priority', { id, message: '매장에서 우선 확인을 요청했습니다.' }); changed('확인 요청을 보냈습니다.'); }));
  S.action('wf-help', safe(id => { F.run('task.priority', { id, message: '현재 방문 업무를 확인해 주세요.' }, 'driver'); S.toast('매장에 확인 요청을 보냈습니다.'); }));
  S.action('wf-ack', safe(id => { S.notificationRuntime.driver.execute(window.SkiNotificationClient.command('ack', {}, id)); S.render(); }));
  S.action('wf-notices', () => S.notifications.open());
  S.action('wf-date', value => { ui.date = value.endsWith('tomorrow') ? S.data.day(1) : S.data.today; ui.selected = null; S.render(); });
  S.change('wf-date', value => { ui.date = value; ui.selected = null; S.render(); });
  S.action('wf-basis', value => { ui.basis = value; S.render(); });
  S.action('wf-correct', safe(id => { const m = F.store.history().movements.find(x => x.id === id); openPicker('잘못 기록한 수량 되돌리기', F.assets(m.assetIds.filter(id => !m.reversedAssetIds.includes(id))), ids => { F.run('movement.undo', { movementId: id, assetIds: ids, reason: read('wf-reason') }); changed('정정했습니다. 이후 이동이 있는 물품은 되돌릴 수 없습니다.'); }, field('정정 사유', '', 'text', 'id="wf-reason" placeholder="예: 수거 수량을 1개 많이 입력"')); }));
  // Reservations: one representative, any number of date/type rows.
  let booking = null;
  function bookingModal() { modal('리프트권 예약 입력', '<div class="wf-form-grid">' + field('대표자 이름', booking.customer.name, 'text', 'id="wf-book-name"') + field('연락처', booking.customer.phone, 'tel', 'id="wf-book-phone"') + '</div><div id="wf-book-lines">' + booking.lines.map((l, i) => '<section class="wf-book-line"><div class="wf-form-grid">' + field('이용일', l.useDate, 'date', 'data-book-date="' + i + '"') + field('발권일', l.issueDate, 'date', 'data-book-issue="' + i + '"') + field('이용 시작', l.startTime || '09:00', 'time', 'data-book-time="' + i + '"') + '</div><div class="wf-book-counts">' + [3, 4, 6].map(h => '<label>' + h + '시간권' + countInput(h + '시간권 ' + (i + 1) + '일', 'wf-book-' + i + '-' + h, l[h]) + '</label>').join('') + '</div>' + (i ? b('이 날짜 삭제', 'wf-book-remove', String(i)) : '') + '</section>').join('') + '</div>' + b('이용일 추가', 'wf-book-add'), b('취소', 'close') + b('예약 저장', 'wf-book-save', '', 'primary')); }
  function readBooking() { booking.customer = { name: read('wf-book-name'), phone: read('wf-book-phone') }; booking.lines.forEach((l, i) => { l.useDate = S.$('[data-book-date="' + i + '"]').value; l.issueDate = S.$('[data-book-issue="' + i + '"]').value; l.startTime = S.$('[data-book-time="' + i + '"]').value; for (const h of [3, 4, 6]) l[h] = number('wf-book-' + i + '-' + h); }); }
  S.action('wf-cancelled-list', safe(() => { const rows = F.snap().reservations.flatMap(r => r.lines.filter(l => l.cancelledQuantity).map(l => row(e(r.customer.name) + ' · ' + e(l.useDate), e(F.snap().catalog.find(s => s.id === l.ticketType).label) + ' 취소 ' + l.cancelledQuantity + '매', b('취소분 복원', 'wf-book-restore-open', r.id + '|' + l.id)))); modal('취소한 예약', rows.join('') || empty('취소 내역이 없습니다.'), b('닫기', 'close')); }));
  S.action('wf-book-restore-open', safe(value => { const { r, line } = bookingLine(value); modal('예약 복원 · ' + r.customer.name, row('복원 수량', '보유권은 다시 배정해야 합니다.', countInput('복원', 'wf-restore-qty', line.cancelledQuantity, line.cancelledQuantity)), b('취소', 'close') + b('예약 복원', 'wf-book-restore', value, 'primary')); }));
  S.action('wf-book-restore', safe(value => { const { r, line } = bookingLine(value); F.run('reservation.restore', { reservationId: r.id, lineId: line.id, quantity: number('wf-restore-qty') }); changed('예약을 복원했습니다. 보유권 배정을 확인해 주세요.'); }));
  S.action('wf-book-new', () => { booking = { customer: { name: '', phone: '' }, lines: [{ useDate: ui.date, issueDate: ui.date, 3: 0, 4: 0, 6: 0 }] }; bookingModal(); });
  S.action('wf-book-add', safe(() => { readBooking(); const date = window.SkiWorkflowCommon.nextDate(booking.lines.at(-1).useDate); booking.lines.push({ useDate: date, issueDate: date, 3: 0, 4: 0, 6: 0 }); bookingModal(); }));
  S.action('wf-book-remove', safe(i => { readBooking(); booking.lines.splice(+i, 1); bookingModal(); }));
  S.action('wf-book-save', safe(() => { readBooking(); const lines = booking.lines.flatMap((l, i) => [3, 4, 6].filter(h => l[h]).map(h => ({ id: 'line-' + i + '-' + h, useDate: l.useDate, issueDate: l.issueDate, ticketType: 'ticket-' + h + 'h', quantity: l[h], startTime: l.startTime, endTime: String(Number(l.startTime.slice(0, 2)) + h).padStart(2, '0') + l.startTime.slice(2) }))); F.run('reservation.create', { id: C.randomId('reservation-'), customer: booking.customer, lines }); changed('예약을 저장했습니다.'); }));
  const bookingLine = value => { const [id, lineId] = value.split('|'), r = F.snap().reservations.find(r => r.id === id); return { r, line: r.lines.find(l => l.id === lineId) }; };
  function bookDetail(value) {
    const { r, line } = bookingLine(value), state = F.snap(), active = state.allocations.filter(a => a.reservationId === r.id && a.lineId === line.id && a.status === 'active');
    modal(r.customer.name + ' · 발권·배정', row(e(F.snap().catalog.find(x => x.id === line.ticketType)?.label || line.ticketType) + ' · 예약 ' + (line.quantity - line.cancelledQuantity) + '매', '이용 ' + e(line.useDate) + ' · ' + (line.startTime ? line.startTime + '~' + line.endTime : '시간 미지정 (날짜 전체)')) + '<div class="wf-actions">' + b('신규 발권', 'wf-book-issue', value) + b('보유권 배정', 'wf-book-allocate', value) + '</div>' + (active.length ? '<p>배정 ' + active.length + '매 · ' + textItems(active.map(a => a.assetId)) + '</p><div class="wf-actions">' + b('차량 배달 등록', 'wf-book-task', value) + b('매장 직접 전달', 'wf-book-direct', value) + b('배정 해제', 'wf-book-release', value) + '</div>' : '<p class="wf-hint">보유권을 배정하거나 실제 발권 수량을 등록하세요.</p>'), b('닫기', 'close'));
  }
  S.action('wf-book-detail', safe(bookDetail));
  S.action('wf-book-edit', safe(value => { const { r, line } = bookingLine(value); modal(r.customer.name + ' · 예약 변경', '<div class="wf-form-grid">' + field('이용 시작', line.startTime || '09:00', 'time', 'id="wf-use-from"') + field('이용 종료', line.endTime || '13:00', 'time', 'id="wf-use-to"') + '</div>' + b('이용시간 저장', 'wf-book-time-save', value) + field('발권 예정일', line.issueDate, 'date', 'id="wf-issue-date"') + b('발권일 저장', 'wf-book-date-save', value) + row('일부 또는 전체 취소', '남은 예약 ' + (line.quantity - line.cancelledQuantity) + '매', countInput('취소', 'wf-cancel-qty', 0, line.quantity - line.cancelledQuantity)), b('닫기', 'close') + b('선택 수량 취소', 'wf-book-cancel', value)); }));
  S.action('wf-book-time-save', safe(value => { const { r, line } = bookingLine(value); F.run('reservation.time', { reservationId: r.id, lineId: line.id, startTime: read('wf-use-from'), endTime: read('wf-use-to') }); changed('이용시간을 저장했습니다.'); }));
  S.action('wf-book-date-save', safe(value => { const { r, line } = bookingLine(value); F.run('reservation.issueDate', { id: r.id, lineIds: [line.id], issueDate: read('wf-issue-date') }); changed(); }));
  S.action('wf-book-cancel', safe(value => { const { r, line } = bookingLine(value); F.run('reservation.cancel', { reservationId: r.id, lineId: line.id, quantity: number('wf-cancel-qty') }); changed('예약을 취소했습니다. 실물 위치는 그대로입니다.'); }));
  function ticketFields(line) { return '<div class="wf-form-grid">' + select('실제 권종', [3, 4, 6].map(h => ['ticket-' + h + 'h', h + '시간권']), line?.ticketType || 'ticket-4h', 'id="wf-ticket-sku"') + field('유효 시작', (line?.useDate || ui.date) + 'T' + (line?.startTime || '09:00'), 'datetime-local', 'id="wf-ticket-from"') + field('유효 종료', (line?.useDate || ui.date) + 'T' + (line?.endTime || '13:00'), 'datetime-local', 'id="wf-ticket-to"') + select('다른 고객에게 재전달', [['no', '재전달 불가'], ['yes', '발권처 확인 · 가능']], 'no', 'id="wf-transferable"') + '</div><fieldset class="wf-checks"><legend>사용 가능한 판매 권종</legend>' + [3, 4, 6].map(h => '<label><input type="checkbox" data-ticket-type="ticket-' + h + 'h" ' + ((line?.ticketType || 'ticket-4h') === 'ticket-' + h + 'h' ? 'checked' : '') + '>' + h + '시간</label>').join('') + '</fieldset><p class="wf-hint">실제 권의 유효 조건을 확인해서 입력하세요.</p>' + row('등록 수량', '', countInput('발권', 'wf-ticket-qty', 1)); }
  let ticketTarget = null;
  S.action('wf-ticket-new', () => { ticketTarget = null; modal('이미 발권한 보유권 등록', ticketFields(), b('취소', 'close') + b('보유권 등록', 'wf-ticket-save', '', 'primary')); });
  S.action('wf-book-issue', safe(value => { ticketTarget = value; const { line } = bookingLine(value); modal('실제 발권 수량 등록', ticketFields(line), b('취소', 'close') + b('발권 완료 기록', 'wf-ticket-save', '', 'primary')); }));
  S.action('wf-ticket-save', safe(() => { const sku = read('wf-ticket-sku'), quantity = number('wf-ticket-qty'), ticket = { validFrom: read('wf-ticket-from') + ':00+09:00', validTo: read('wf-ticket-to') + ':00+09:00', acceptedTypes: [...S.root.querySelectorAll('[data-ticket-type]:checked')].map(el => el.dataset.ticketType), transferable: read('wf-transferable') === 'yes', vendorId: 'resort' }; let extra = {}; if (ticketTarget?.legacy) { const [orderId, itemId] = ticketTarget.legacy.split('|'); F.issueLegacyTicket(orderId, itemId, { sku, quantity, ticket }); changed('리프트권 실제 발권·지급을 기록했습니다.'); return; } if (ticketTarget) { const { r, line } = bookingLine(ticketTarget); extra = { reservationId: r.id, lineId: line.id }; } F.run(ticketTarget ? 'ticket.issue' : 'stock.opening', { sku, quantity, ticket, ...extra }); changed('실제 발권한 권을 매장 보관으로 기록했습니다.'); }));
  S.action('wf-book-allocate', safe(value => { const { r, line } = bookingLine(value), raw = S.sharedRepository.workflows(F.shopId); const candidates = F.snap().assets.filter(a => a.ticket && !window.SkiWorkflowReservations.eligible(raw, a, r.id, line.id)); openPicker('보유권 배정 · ' + r.customer.name, candidates, ids => { F.run('ticket.allocate', { reservationId: r.id, lineId: line.id, assetIds: ids }); changed('보유권을 배정했습니다. 고객에게 있는 권은 회수 대기로 표시합니다.'); }); }));
  S.action('wf-book-release', safe(value => { const { r, line } = bookingLine(value), allocations = F.snap().allocations.filter(a => a.reservationId === r.id && a.lineId === line.id && a.status === 'active'); openPicker('권 배정 해제', F.assets(allocations.map(a => a.assetId)), ids => { F.run('ticket.release', { allocationIds: allocations.filter(a => ids.includes(a.assetId)).map(a => a.id) }); changed(); }); }));
  S.action('wf-next', safe(id => { const a = F.snap().assets.find(a => a.id === id), raw = S.sharedRepository.workflows(F.shopId); const options = F.snap().reservations.flatMap(r => r.lines.filter(l => !window.SkiWorkflowReservations.eligible(raw, a, r.id, l.id)).map(l => row(e(r.customer.name), e(l.useDate) + ' · ' + (l.startTime ? l.startTime + '~' + l.endTime : '날짜 전체'), b('이 고객 선택', 'wf-book-allocate', r.id + '|' + l.id)))); modal('다음 고객 선택', options.join('') || empty('유효시간에 맞는 예약이 없습니다. 예약에서 이용 시간을 확인해 주세요.'), b('닫기', 'close')); }));
  S.action('wf-book-task', safe(value => { const { r, line } = bookingLine(value); modal(r.customer.name + ' · 전달 업무', field('전달 시간', line.startTime || '09:00', 'time', 'id="wf-delivery-time"') + field('전달 장소', '만선 광장', 'text', 'id="wf-delivery-place"'), b('닫기', 'close') + b('배달 업무 저장', 'wf-book-task-save', value, 'primary')); }));
  S.action('wf-book-task-save', safe(value => { const { r, line } = bookingLine(value), assetIds = F.snap().allocations.filter(a => a.reservationId === r.id && a.lineId === line.id && a.status === 'active' && !a.fulfilledAt).map(a => a.assetId); if (!assetIds.length) throw new Error('전달할 권을 먼저 배정해 주세요.'); const existing = F.snap().tasks.find(t => t.reservationId === r.id && t.customerId === r.id && t.status === 'waiting' && t.kind === 'delivery' && t.id.endsWith(line.id)); F.saveTask({ id: existing?.id || ('delivery-' + r.id + '-' + line.id).slice(0, 79), kind: 'delivery', reservationId: r.id, customerId: r.id, title: r.customer.name + ' 권 전달', date: line.useDate, time: read('wf-delivery-time'), place: read('wf-delivery-place'), assetIds }); changed('배달 업무를 저장했습니다. 매장 보관권은 차량 적재에서 실어 주세요.'); }));
  S.action('wf-book-direct', safe(value => { const { r, line } = bookingLine(value), ids = F.snap().allocations.filter(a => a.reservationId === r.id && a.lineId === line.id && a.status === 'active' && !a.fulfilledAt).map(a => a.assetId); movement('deliver', F.assets(ids).filter(a => a.location.kind === 'shop'), { from: F.shop, to: { kind: 'customer', id: r.id } }); }));
  function returnsPage() { const knownCustomers = [...F.orders.keys(), ...F.store.history().movements.filter(m => m.kind === 'deliver').map(m => m.to.id), ...F.snap().assets.filter(a => a.location.kind === 'customer').map(a => a.location.id)]; const customers = new Set(knownCustomers.filter(customerId => ![...F.orders.keys()].some(id => id !== customerId && F.customerIds(id).includes(customerId)))); return '<div class="wf">' + head('반납 확인', '고객 보유 → 차량 수거 → 매장 인계를 같은 기록으로 확인합니다.', go('차량 인계 확인', 'vehicle-stock', '', 'primary')) + '<div class="wf-toolbar"><input type="search" aria-label="반납 고객 찾기" placeholder="이름 또는 연락처" data-search="wf-returns" value="' + e(ui.returnQuery) + '">' + select('반납 상태', [['all', '전체'], ['customer', '고객 미반납'], ['vehicle', '매장 확인 대기']], ui.returnFilter, 'data-change="wf-return-filter"') + '</div><div class="wf-scroll" id="wf-return-list">' + [...customers].filter(id => { const customer = S.workflowCustomer(id), o = F.projectOrder(id); return (!ui.returnQuery || (customer.name + customer.phone).replace(/-/g, '').includes(ui.returnQuery.replace(/-/g, ''))) && (ui.returnFilter === 'all' || (ui.returnFilter === 'vehicle' ? o?.totals.vehicleQuantity > 0 : F.snap().assets.some(a => a.location.kind === 'customer' && F.customerIds(id).includes(a.location.id)))); }).map(id => { const o = F.projectOrder(id), ids = F.snap().assets.filter(a => a.location.kind === 'customer' && F.customerIds(id).includes(a.location.id)).map(a => a.id); return row(e(name(id)), '고객 보유: ' + textItems(ids) + (o ? '<br>차량 보관 ' + o.totals.vehicleQuantity + '개 · 매장 확인 ' + o.totals.shopQuantity + '개 · 지급 전 ' + o.totals.unissuedQuantity + '개' : ''), go('상세·반납 처리', 'return-detail', id)); }).join('') + '</div></div>'; }
  function returnDetail() { const id = S.state.params.id, o = F.projectOrder(id), customer = S.workflowCustomer(id), held = F.snap().assets.filter(a => a.location.kind === 'customer' && F.customerIds(id).includes(a.location.id)); return '<div class="wf">' + head(e(customer.name) + ' · 반납 확인', e(customer.phone || ''), go('반납 목록', 'returns')) + '<div class="wf-scroll">' + panel('고객에게 남은 물품', unitCards(held.map(a => a.id)), b('매장 직접반납', 'wf-direct-return', id, 'primary')) + (o ? panel('품목별 현황', o.items.map(i => row(e(i.label), '고객 ' + i.customerQuantity + ' · 차량 ' + i.vehicleQuantity + ' · 매장 ' + i.shopQuantity + ' · 지급 전 ' + i.unissuedQuantity)).join(''), (o.totals.unissuedQuantity ? b('장비 지급 확인', 'wf-order-issue', id) + b('장비 적재·배달', 'wf-order-load', id) : '') + go('차량 인계', 'vehicle-stock') + (o.items.some(i => i.category === 'liftTicket' && i.unissuedQuantity) ? b('리프트권 지급', 'wf-legacy-ticket', id) : '')) : '') + panel('수거 일정', F.snap().tasks.filter(t => t.customerId === id && t.kind === 'collection' && t.status === 'waiting').map(t => row(e(t.date) + ' ' + e(t.time), e(t.place), b('일정 변경', 'wf-task-edit', t.id))).join('') || empty('등록된 수거 일정이 없습니다.'), held.length ? b('수거 일정 추가', 'wf-collection-new', id) : '') + '</div></div>'; }
  S.action('wf-legacy-ticket', safe(id => { const o = F.projectOrder(id); modal('리프트권 지급 · ' + o.customer.name, '<p>실제 권종과 유효시간을 선택해 주세요.</p>' + o.items.filter(i => i.category === 'liftTicket' && i.unissuedQuantity).map(i => row(e(i.label) + ' ' + i.unissuedQuantity + '매', i.returnPlan.date, b('발권·지급', 'wf-legacy-ticket-issue', id + '|' + i.id))).join(''), b('닫기', 'close')); }));
  S.action('wf-legacy-ticket-issue', safe(value => { ticketTarget = { legacy: value }; modal('실제 발권·지급 수량', ticketFields(), b('취소', 'close') + b('지급 확인', 'wf-ticket-save', '', 'primary')); }));
  S.search('wf-returns', value => { ui.returnQuery = value; const parser = document.createElement('div'); parser.innerHTML = returnsPage(); S.$('#wf-return-list').innerHTML = parser.querySelector('#wf-return-list').innerHTML; S.icons(); });
  S.change('wf-return-filter', value => { ui.returnFilter = value; S.render(); });
  S.action('wf-direct-return', safe(id => UdirectReturn(id)));
  function UdirectReturn(id) { openPicker('매장 직접반납', F.snap().assets.filter(a => a.location.kind === 'customer' && F.customerIds(id).includes(a.location.id)), ids => { F.returnCustomer(id, ids); changed('매장 반납을 기록했습니다. 해당 수거 예정 수량도 반영했습니다.'); }); }
  S.action('rental-return', safe(id => S.go('return-detail', { id })));
  S.action('wf-order-load', safe(id => { const base = S.data.orders.find(o => o.id === id); modal('장비 적재·배달', field('배달 날짜', base?.pickup || S.data.today, 'date', 'id="wf-order-date"') + field('배달 시간', base?.pickupTime || '09:00', 'time', 'id="wf-order-time"') + field('배달 장소', base?.deliveryPlace || '만선 광장', 'text', 'id="wf-order-place"'), b('취소', 'close') + b('실제 적재 완료', 'wf-order-load-save', id, 'primary')); }));
  S.action('wf-order-load-save', safe(id => { F.dispatchOrder(id, { date: read('wf-order-date'), time: read('wf-order-time'), place: read('wf-order-place') }); changed('장비를 차량에 적재하고 배달 업무를 등록했습니다.'); }));
  S.action('wf-order-issue', safe(id => { F.issueOrder(id); changed('실제 장비 지급을 기록했습니다.'); }));
  let taskDraft = null;
  function taskEditor(t) { taskDraft = t; modal('수거 일정', '<div class="wf-form-grid">' + field('날짜', t.date, 'date', 'id="wf-task-date"') + field('시간', t.time, 'time', 'id="wf-task-time"') + field('장소', t.place, 'text', 'id="wf-task-place"') + '</div>', b('취소', 'close') + b('일정 저장', 'wf-task-save', '', 'primary')); }
  S.action('wf-task-cancel', safe(id => { const t = F.snap().tasks.find(t => t.id === id); modal('방문 업무 취소', '<p>' + e(t.title) + ' · ' + e(t.place) + '</p><p>처리한 물품 위치는 유지하고, 남은 방문을 취소합니다.</p>', b('돌아가기', 'close') + b('업무 취소', 'wf-task-cancel-save', id)); }));
  S.action('wf-task-cancel-save', safe(id => { F.run('task.status', { id, status: 'cancelled' }); changed('남은 방문 업무를 취소했습니다.'); }));
  S.action('wf-task-edit', safe(id => taskEditor(F.taskPayload(F.snap().tasks.find(t => t.id === id)))));
  S.action('wf-collection-new', safe(id => taskEditor({ id: C.randomId('collection-'), kind: 'collection', customerId: id, vehicleId: F.vehicleId, date: S.data.today, time: '16:30', place: '만선 광장', title: name(id) + ' 수거', assetIds: F.snap().assets.filter(a => a.location.kind === 'customer' && F.customerIds(id).includes(a.location.id)).map(a => a.id) })));
  S.action('wf-task-save', safe(() => { F.saveTask({ ...taskDraft, date: read('wf-task-date'), time: read('wf-task-time'), place: read('wf-task-place') }); changed('수거 일정을 변경했습니다.'); }));
  S.register('vehicle', { title: '1호 차량', headerTools: vehicleHeaderTools, render: renderVehicle });
  S.register('vehicle-stock', { title: '차량 적재·인계', parent: 'dispatch', render: vehicleStockPage });
  S.register('lift-reservations', { title: '리프트권 예약', render: reservations });
  S.register('lift-stock', { title: '리프트권 보관·환불', parent: 'lift-reservations', render: liftStock });
  S.returnUI.closingTickets = () => { const report = F.store.report({ date: S.data.today }); return panel('리프트권 이동 집계', report.totals.filter(x => x.newlyIssued || x.recovered || x.refunded || x.redelivered).map(x => row(e(F.snap().catalog.find(s => s.id === x.sku)?.label || x.sku), '신규 발권 ' + x.newlyIssued + ' · 회수 ' + x.recovered + ' · 재전달 ' + x.redelivered + ' · 발권처 환불 ' + x.refunded)).join('') + row('실제 발권처 환불액', S.money(report.refundAmountWon)) + '<p class="wf-hint">고객 결제 환불 및 장당 회수 기준 금액과 별도 집계입니다.</p>'); };
  S.workflowUI = { openNotice: notice => { if (notice.formId) S.go('response', { id: notice.formId }); else if (notice.taskId) { ui.selected = notice.taskId; if (S.state.page === 'vehicle') openTask(notice.taskId); else { S.go('dispatch'); S.dispatchBoard?.selectTask(notice.taskId); } } else if (notice.refundId) S.go('lift-stock'); else if (notice.movementId) S.go(S.state.page === 'vehicle' ? 'vehicle' : 'vehicle-stock'); else S.go('dispatch'); }, openTask, safe, modal, head, panel, row, countInput, read, number, changed, textItems, empty, openPicker, stock, stamp, syncBase };
})();
